# ╔══════════════════════════════════════════════════════════════════════════════╗
# ║                     SYSMON CONFIGURATION - Centralized Settings              ║
# ╚══════════════════════════════════════════════════════════════════════════════╝
#
# All sysmon configuration in one place. No magic numbers!
# Import this file in sysmon.nix and sysmon-hm.nix.
#
# Icons use Unicode escape sequences to avoid corruption when processed by
# Nix strings or shell heredocs. The reader script interprets these with printf.
#
{
  # ════════════════════════════════════════════════════════════════════════════
  # DAEMON SETTINGS
  # ════════════════════════════════════════════════════════════════════════════

  daemon = {
    # Sampling interval in milliseconds
    intervalMs = 5000;

    # Output directories (platform-specific)
    linuxDir = "/dev/shm/sysmon";
    darwinDir = "/tmp/sysmon";
  };

  # ════════════════════════════════════════════════════════════════════════════
  # READER / DISPLAY SETTINGS
  # ════════════════════════════════════════════════════════════════════════════

  display = {
    # Maximum character budget for metrics display
    maxBudget = 45;

    # Minimum terminal width to show metrics (hidden if narrower)
    # Set to 0 to always show
    minTerminalWidth = 0;

    # Seconds after which daemon data is considered stale (shows "?")
    staleThresholdSec = 10;

    # Spacer between icon and value (e.g., " 42%" vs " 42%")
    # Common values: " " (space), "" (no space), " " (thin space)
    spacerIconValue = "";

    # Spacer between metrics (e.g., "42%  67%" vs "42% 67%")
    # Common values: " " (single space), "  " (double space), " │ " (separator)
    spacerMetrics = " ";
  };

  # ════════════════════════════════════════════════════════════════════════════
  # ICONS - Nerd Font (Documentation Only)
  # ════════════════════════════════════════════════════════════════════════════
  # Actual icons are stored in sysmon-icons.sh (generated by Python).
  # This avoids Unicode corruption when processing through Nix/shell.
  #
  # To change icons, edit sysmon-icons.sh using Python:
  #   python3 -c "print('\uf4bc')"  # Test the character first
  #
  # Find icons at: https://www.nerdfonts.com/cheat-sheet
  #
  # Current icons (for reference):
  #   CPU:  nf-oct-cpu (\uf4bc)
  #   RAM:  nf-md-memory (\uefc5)
  #   Load: 󰊚 nf-md-pulse (\U000f029a)
  #   Swap: 󰾴 nf-md-swap_horizontal_variant (\U000f0fb4)
  #

  # ════════════════════════════════════════════════════════════════════════════
  # COLORS - ANSI 256 Color Codes
  # ════════════════════════════════════════════════════════════════════════════

  colors = {
    # Normal state - blends into background
    muted = 242; # Gray

    # Elevated state - noticeable but not alarming
    elevated = 255; # White

    # Critical state - demands attention
    critical = 196; # Red
  };

  # ════════════════════════════════════════════════════════════════════════════
  # METRIC DEFINITIONS
  # ════════════════════════════════════════════════════════════════════════════
  # Each metric has:
  #   - thresholds: [elevated, critical] - values that trigger color changes
  #   - priority: higher = more important, shown first when space is limited
  #   - suffix: appended to value (e.g., "%" for percentages)
  #   - type: "int" or "float" for threshold comparison
  #

  metrics = {
    cpu = {
      thresholds = {
        elevated = 50;
        critical = 80;
      };
      priority = 100; # Highest - always show first
      suffix = "%";
      type = "int";
    };

    ram = {
      thresholds = {
        elevated = 70;
        critical = 90;
      };
      priority = 90;
      suffix = "%";
      type = "int";
    };

    load = {
      thresholds = {
        elevated = 2.0;
        critical = 4.0;
      };
      priority = 70;
      suffix = ""; # Load has no suffix
      type = "float";
    };

    swap = {
      thresholds = {
        elevated = 10;
        critical = 50;
      };
      priority = 60; # Lowest - hidden first when space is limited
      suffix = "%";
      type = "int";
      hideIfZero = true; # Don't show if swap is 0%
    };
  };
}
