#!/usr/bin/env bash
# Sysmon Icons - Generated by Python to preserve Unicode
# DO NOT EDIT MANUALLY - Use Python to regenerate if needed
# See: modules/shared/README.md for editing rules
# shellcheck disable=SC2034  # Variables are used when sourced

CPU_ICON=""
RAM_ICON=""
LOAD_ICON="󰊚"
SWAP_ICON="󰾴"
