# ╔══════════════════════════════════════════════════════════════════════════════╗
# ║                   StaSysMo - Starship System Monitoring (NixOS)              ║
# ╚══════════════════════════════════════════════════════════════════════════════╝
#
# Provides system metrics (CPU, RAM, Load, Swap) in the Starship prompt via a
# background daemon that pre-computes values for instant reading.
#
# This is a NixOS module for systemd services. For macOS/Home Manager, use
# home-manager.nix instead.
#
# Usage (NixOS - configuration.nix):
#   imports = [ ../../modules/shared/stasysmo/nixos.nix ];
#   services.stasysmo.enable = true;
#
# Configuration:
#   All defaults are in config.nix. Override via services.stasysmo options.
#
{
  config,
  lib,
  pkgs,
  ...
}:

let
  cfg = config.services.sysmon;

  # Import centralized configuration defaults
  defaultConfig = import ./config.nix;

  # Read icons from file (preserves Unicode - generated by Python)
  # The file contains: CPU_ICON="..." RAM_ICON="..." etc.
  iconsFile = builtins.readFile ./icons.sh;

  # Parse icon from the file (extract value between quotes after KEY=)
  getIconFromFile =
    key:
    let
      # Match: KEY="value"
      regex = "${key}=\"([^\"]+)\"";
      matches = builtins.match ".*${regex}.*" iconsFile;
    in
    if matches != null then builtins.elemAt matches 0 else "?";

  # ════════════════════════════════════════════════════════════════════════════
  # SCRIPT PACKAGES
  # ════════════════════════════════════════════════════════════════════════════

  # Daemon script package
  stasysmo-daemon = pkgs.writeShellScriptBin "stasysmo-daemon" (builtins.readFile ./daemon.sh);

  # Reader script package with configuration from Nix options
  stasysmo-reader = pkgs.writeShellScriptBin "stasysmo-reader" ''
    # Configuration from Nix options (no magic numbers!)
    export STASYSMO_MAX_BUDGET="${toString cfg.display.maxBudget}"
    export STASYSMO_MIN_TERMINAL="${toString cfg.display.minTerminalWidth}"
    export STASYSMO_STALE_THRESHOLD="${toString cfg.display.staleThreshold}"

    # Spacers
    export STASYSMO_SPACER_ICON_VALUE="${cfg.display.spacerIconValue}"
    export STASYSMO_SPACER_METRICS="${cfg.display.spacerMetrics}"

    # Thresholds
    export STASYSMO_CPU_ELEVATED="${toString cfg.metrics.cpu.thresholds.elevated}"
    export STASYSMO_CPU_CRITICAL="${toString cfg.metrics.cpu.thresholds.critical}"
    export STASYSMO_RAM_ELEVATED="${toString cfg.metrics.ram.thresholds.elevated}"
    export STASYSMO_RAM_CRITICAL="${toString cfg.metrics.ram.thresholds.critical}"
    export STASYSMO_LOAD_ELEVATED="${toString cfg.metrics.load.thresholds.elevated}"
    export STASYSMO_LOAD_CRITICAL="${toString cfg.metrics.load.thresholds.critical}"
    export STASYSMO_SWAP_ELEVATED="${toString cfg.metrics.swap.thresholds.elevated}"
    export STASYSMO_SWAP_CRITICAL="${toString cfg.metrics.swap.thresholds.critical}"

    # Icons (Unicode characters from icons.sh)
    export STASYSMO_ICON_CPU="${cfg.icons.cpu}"
    export STASYSMO_ICON_RAM="${cfg.icons.ram}"
    export STASYSMO_ICON_LOAD="${cfg.icons.load}"
    export STASYSMO_ICON_SWAP="${cfg.icons.swap}"

    # Colors
    export STASYSMO_COLOR_MUTED="${toString cfg.colors.muted}"
    export STASYSMO_COLOR_ELEVATED="${toString cfg.colors.elevated}"
    export STASYSMO_COLOR_CRITICAL="${toString cfg.colors.critical}"

    # Run the reader script
    ${builtins.readFile ./reader.sh}
  '';

in
{
  # ════════════════════════════════════════════════════════════════════════════
  # MODULE OPTIONS
  # ════════════════════════════════════════════════════════════════════════════

  options.services.stasysmo = {
    enable = lib.mkEnableOption "StaSysMo system metrics daemon for Starship prompt";

    # ──────────────────────────────────────────────────────────────────────────
    # Daemon Settings
    # ──────────────────────────────────────────────────────────────────────────

    daemon = {
      interval = lib.mkOption {
        type = lib.types.int;
        default = defaultConfig.daemon.intervalMs;
        description = "Sampling interval in milliseconds";
      };
    };

    # ──────────────────────────────────────────────────────────────────────────
    # Display Settings
    # ──────────────────────────────────────────────────────────────────────────

    display = {
      maxBudget = lib.mkOption {
        type = lib.types.int;
        default = defaultConfig.display.maxBudget;
        description = "Maximum character budget for metrics display";
      };

      minTerminalWidth = lib.mkOption {
        type = lib.types.int;
        default = defaultConfig.display.minTerminalWidth;
        description = "Minimum terminal width to show metrics (hidden if narrower)";
      };

      staleThreshold = lib.mkOption {
        type = lib.types.int;
        default = defaultConfig.display.staleThresholdSec;
        description = "Seconds after which data is considered stale";
      };

      spacerIconValue = lib.mkOption {
        type = lib.types.str;
        default = defaultConfig.display.spacerIconValue;
        description = "Spacer string between icon and value (e.g., ' ' or '')";
      };

      spacerMetrics = lib.mkOption {
        type = lib.types.str;
        default = defaultConfig.display.spacerMetrics;
        description = "Spacer string between metrics (e.g., ' ' or '  ')";
      };
    };

    # ──────────────────────────────────────────────────────────────────────────
    # Icons (read from sysmon-icons.sh to preserve Unicode)
    # ──────────────────────────────────────────────────────────────────────────

    icons = {
      cpu = lib.mkOption {
        type = lib.types.str;
        default = getIconFromFile "CPU_ICON";
        description = "Icon for CPU metric (Nerd Font character)";
      };

      ram = lib.mkOption {
        type = lib.types.str;
        default = getIconFromFile "RAM_ICON";
        description = "Icon for RAM metric (Nerd Font character)";
      };

      load = lib.mkOption {
        type = lib.types.str;
        default = getIconFromFile "LOAD_ICON";
        description = "Icon for load metric (Nerd Font character)";
      };

      swap = lib.mkOption {
        type = lib.types.str;
        default = getIconFromFile "SWAP_ICON";
        description = "Icon for swap metric (Nerd Font character)";
      };
    };

    # ──────────────────────────────────────────────────────────────────────────
    # Colors (ANSI 256)
    # ──────────────────────────────────────────────────────────────────────────

    colors = {
      muted = lib.mkOption {
        type = lib.types.int;
        default = defaultConfig.colors.muted;
        description = "ANSI 256 color for normal state (blends in)";
      };

      elevated = lib.mkOption {
        type = lib.types.int;
        default = defaultConfig.colors.elevated;
        description = "ANSI 256 color for elevated state (noticeable)";
      };

      critical = lib.mkOption {
        type = lib.types.int;
        default = defaultConfig.colors.critical;
        description = "ANSI 256 color for critical state (urgent)";
      };
    };

    # ──────────────────────────────────────────────────────────────────────────
    # Metric Thresholds
    # ──────────────────────────────────────────────────────────────────────────

    metrics = {
      cpu = {
        thresholds = {
          elevated = lib.mkOption {
            type = lib.types.int;
            default = defaultConfig.metrics.cpu.thresholds.elevated;
            description = "CPU% threshold for elevated color";
          };
          critical = lib.mkOption {
            type = lib.types.int;
            default = defaultConfig.metrics.cpu.thresholds.critical;
            description = "CPU% threshold for critical color";
          };
        };
      };

      ram = {
        thresholds = {
          elevated = lib.mkOption {
            type = lib.types.int;
            default = defaultConfig.metrics.ram.thresholds.elevated;
            description = "RAM% threshold for elevated color";
          };
          critical = lib.mkOption {
            type = lib.types.int;
            default = defaultConfig.metrics.ram.thresholds.critical;
            description = "RAM% threshold for critical color";
          };
        };
      };

      load = {
        thresholds = {
          elevated = lib.mkOption {
            type = lib.types.number;
            default = defaultConfig.metrics.load.thresholds.elevated;
            description = "Load average threshold for elevated color";
          };
          critical = lib.mkOption {
            type = lib.types.number;
            default = defaultConfig.metrics.load.thresholds.critical;
            description = "Load average threshold for critical color";
          };
        };
      };

      swap = {
        thresholds = {
          elevated = lib.mkOption {
            type = lib.types.int;
            default = defaultConfig.metrics.swap.thresholds.elevated;
            description = "Swap% threshold for elevated color";
          };
          critical = lib.mkOption {
            type = lib.types.int;
            default = defaultConfig.metrics.swap.thresholds.critical;
            description = "Swap% threshold for critical color";
          };
        };
      };
    };
  };

  # ════════════════════════════════════════════════════════════════════════════
  # NIXOS CONFIGURATION (systemd)
  # ════════════════════════════════════════════════════════════════════════════

  config = lib.mkIf cfg.enable {
    # Install scripts to PATH
    environment.systemPackages = [
      stasysmo-daemon
      stasysmo-reader
    ];

    # Systemd service
    systemd.services.stasysmo-daemon = {
      description = "StaSysMo - Starship System Monitoring daemon";
      wantedBy = [ "multi-user.target" ];
      after = [ "local-fs.target" ];

      serviceConfig = {
        Type = "simple";
        Restart = "always";
        RestartSec = 5;
        ExecStart = "${stasysmo-daemon}/bin/stasysmo-daemon ${toString cfg.daemon.interval}";

        # Security hardening
        DynamicUser = true;
        RuntimeDirectory = "sysmon";
        RuntimeDirectoryMode = "0755";

        # Allow writing to /dev/shm
        ReadWritePaths = [ "/dev/shm" ];

        # Minimal capabilities
        CapabilityBoundingSet = "";
        NoNewPrivileges = true;
        ProtectSystem = "strict";
        ProtectHome = true;
        PrivateTmp = true;
        PrivateDevices = true;
        ProtectKernelTunables = true;
        ProtectKernelModules = true;
        ProtectControlGroups = true;
      };
    };
  };
}
