# ╔══════════════════════════════════════════════════════════════════════════════╗
# ║                   macOS Home Manager Template                               ║
# ╚══════════════════════════════════════════════════════════════════════════════╝
#
# Copy this directory to create a new macOS host:
#   cp -r hosts/_template-macos hosts/YOUR-HOSTNAME
#
# Then customize:
#   1. Update theme.hostname below
#   2. Update home.username and home.homeDirectory
#   3. Update Git identity
#   4. Fix architecture in home.packages (x86_64 vs aarch64)
#   5. Add host to theme-palettes.nix
#   6. Add host to flake.nix
#
# See docs/MACOS-SETUP.md for detailed instructions.
#
{
  pkgs,
  lib,
  inputs,
  ...
}:

{
  # ============================================================================
  # Module Imports
  # ============================================================================
  imports = [
    ../../modules/uzumaki/home-manager.nix
  ];

  # ============================================================================
  # UZUMAKI MODULE - Fish functions, theming, monitoring
  # ============================================================================
  uzumaki = {
    enable = true;
    role = "workstation";
    fish.editor = "nano"; # Options: nano, vim, code, etc.
    stasysmo.enable = true; # System metrics in Starship prompt
  };

  # ============================================================================
  # THEME - Must match actual hostname
  # ============================================================================
  # Also add entry to: modules/uzumaki/theme/theme-palettes.nix
  theme.hostname = "CHANGE-ME"; # ← REQUIRED: Set to actual hostname

  # ============================================================================
  # USER SETTINGS
  # ============================================================================
  home.username = "markus"; # ← Change if different user
  home.homeDirectory = "/Users/markus"; # ← Change if different user

  home.stateVersion = "24.11";
  home.enableNixpkgsReleaseCheck = false;
  programs.home-manager.enable = true;

  # ============================================================================
  # Fish Shell Configuration
  # ============================================================================
  programs.fish = {
    enable = true;

    shellInit = ''
      # Environment variables
      set -gx TERM xterm-256color
      set -gx EDITOR nano

      # zoxide integration
      set -gx ZOXIDE_CMD z

      # Add Nix profile completions
      if test -d ~/.nix-profile/share/fish/vendor_completions.d
        set -p fish_complete_path ~/.nix-profile/share/fish/vendor_completions.d
      end
    '';

    loginShellInit = ''
      # Ensure Nix paths are prioritized
      fish_add_path --prepend --move ~/.nix-profile/bin
      fish_add_path --prepend --move /nix/var/nix/profiles/default/bin
    '';

    interactiveShellInit = ''
      # Custom greeting
      function fish_greeting
          set_color cyan
          echo -n "Welcome to fish, the friendly interactive shell "
          set_color green
          echo -n (whoami)"@"(hostname -s)
          set_color yellow
          echo -n " · "(date "+%Y-%m-%d %H:%M")
          set_color normal
      end

      # Initialize zoxide
      zoxide init fish | source
    '';

    # Additional functions (pingt, sourcefish, etc. from uzumaki)
    functions = {
      # Custom cd using zoxide
      cd = ''
        if set -q ZOXIDE_CMD
            z $argv
        else
            builtin cd $argv
        end
      '';

      # Sudo with !! support
      sudo = {
        description = "Sudo with !! support";
        body = ''
          if test "$argv" = "!!"
              eval command sudo $history[1]
          else
              command sudo $argv
          end
        '';
      };

      # Homebrew maintenance (macOS-specific)
      brewall = ''
        brew update
        brew upgrade
        brew cleanup
        brew doctor
      '';
    };

    # macOS-specific aliases
    shellAliases = {
      mc = "env LANG=en_US.UTF-8 mc";
      # Force macOS native ping (inetutils has bugs on Darwin)
      ping = "/sbin/ping";
      traceroute = "/usr/sbin/traceroute";
      netstat = "/usr/sbin/netstat";
    };

    # macOS-specific abbreviations
    shellAbbrs = {
      flushdns = "sudo killall -HUP mDNSResponder && echo macOS DNS Cache Reset";
    };
  };

  # ============================================================================
  # Starship Prompt (config generated by theme-hm.nix)
  # ============================================================================
  programs.starship = {
    enable = true;
    enableFishIntegration = true;
    enableBashIntegration = true;
  };

  # ============================================================================
  # WezTerm Terminal
  # ============================================================================
  programs.wezterm = {
    enable = true;
    extraConfig = ''
      local wezterm = require("wezterm")
      local act = wezterm.action
      local config = wezterm.config_builder()

      -- Fonts
      config.font_size = 12
      config.line_height = 1.1
      config.font = wezterm.font("Hack Nerd Font Mono")

      -- Colors
      config.color_scheme = "tokyonight_night"
      config.colors = {
          cursor_bg = "#7aa2f7",
          cursor_border = "#7aa2f7",
          cursor_fg = "black",
      }
      config.default_cursor_style = "BlinkingBar"

      -- Window
      config.window_decorations = "RESIZE|INTEGRATED_BUTTONS"
      config.hide_tab_bar_if_only_one_tab = false
      config.native_macos_fullscreen_mode = true
      config.window_background_opacity = 0.9
      config.macos_window_background_blur = 10
      config.window_padding = { left = 8, right = 8, top = 8, bottom = 8 }
      config.initial_cols = 160
      config.initial_rows = 48

      -- Behavior
      config.adjust_window_size_when_changing_font_size = false
      config.audible_bell = "Disabled"
      config.send_composed_key_when_left_alt_is_pressed = true
      config.send_composed_key_when_right_alt_is_pressed = true

      -- Keys
      config.keys = {
          { key = "c", mods = "CMD", action = act.CopyTo("Clipboard") },
          { key = "v", mods = "CMD", action = act.PasteFrom("Clipboard") },
          { key = "-", mods = "CMD", action = act.DecreaseFontSize },
          { key = "0", mods = "CMD", action = act.ResetFontSize },
          { key = "=", mods = "CMD", action = act.IncreaseFontSize },
          { key = "f", mods = "CMD|CTRL", action = act.ToggleFullScreen },
          { key = "t", mods = "CMD", action = act.SpawnTab("CurrentPaneDomain") },
          { key = "w", mods = "CMD", action = act.CloseCurrentPane({ confirm = true }) },
          { key = "n", mods = "CMD", action = act.SpawnWindow },
      }

      return config
    '';
  };

  # ============================================================================
  # Git Configuration
  # ============================================================================
  programs.git = {
    enable = true;

    ignores = [
      "*~"
      ".DS_Store"
    ];

    settings = {
      # Default identity - CUSTOMIZE THIS
      user = {
        name = "Your Name"; # ← CHANGE THIS
        email = "your@email.com"; # ← CHANGE THIS
      };

      credential.helper = "osxkeychain";
    };

    # Optional: Dual identity for work machines
    # includes = [
    #   {
    #     condition = "gitdir:~/Code/COMPANY/";
    #     contents.user = {
    #       name = "Work Name";
    #       email = "work@company.com";
    #     };
    #   }
    # ];
  };

  # ============================================================================
  # Zsh (System Shell Fallback)
  # ============================================================================
  programs.zsh = {
    enable = true;
    initExtra = ''
      export PATH="$HOME/.nix-profile/bin:/nix/var/nix/profiles/default/bin:$PATH"
    '';
  };

  # ============================================================================
  # Direnv (Project Environment Loading)
  # ============================================================================
  programs.direnv = {
    enable = true;
    nix-direnv.enable = true;
  };

  # ============================================================================
  # Packages
  # ============================================================================
  home.packages = with pkgs; [
    # System Tools
    # ⚠️ FIX ARCHITECTURE: Use aarch64-darwin for Apple Silicon
    inputs.agenix.packages.x86_64-darwin.default # Intel
    # inputs.agenix.packages.aarch64-darwin.default  # Apple Silicon (M1/M2/M3)

    # Interpreters
    nodejs
    python3

    # CLI Development Tools
    gh
    jq
    just
    lazygit

    # File Management
    tree
    pv
    tealdeer
    fswatch
    mc

    # Terminal Tools
    zellij
    eza

    # Networking
    netcat
    wakeonlan
    speedtest-go
    websocat

    # Text Processing
    lynx
    html2text

    # Backup & Archive
    restic
    rage

    # macOS Built-in Overrides
    rsync
    wget

    # CLI Tools
    zoxide
    bat
    btop
    ripgrep
    fd
    fzf
    prettier
    nano

    # Fonts
    (pkgs.nerd-fonts.hack)
  ];

  # Enable fontconfig
  fonts.fontconfig.enable = true;

  # Install Hack Nerd Font for macOS
  home.activation.installMacOSFonts = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    echo "Installing Hack Nerd Font for macOS..."
    mkdir -p "$HOME/Library/Fonts"

    FONT_PATH="${pkgs.nerd-fonts.hack}/share/fonts/truetype/NerdFonts/Hack"

    if [ -d "$FONT_PATH" ]; then
      for font in "$FONT_PATH"/*.ttf; do
        if [ -f "$font" ]; then
          font_name=$(basename "$font")
          target="$HOME/Library/Fonts/$font_name"
          if [ -L "$target" ]; then rm "$target"; fi
          if [ ! -e "$target" ]; then
            ln -sf "$font" "$target"
            echo "  Linked: $font_name"
          fi
        fi
      done
      echo "✅ Hack Nerd Font installed for macOS"
    fi
  '';

  # Link macOS GUI Applications
  home.activation.linkMacOSApps = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    echo "Linking macOS GUI applications..."
    mkdir -p "$HOME/Applications"

    apps=("WezTerm.app")

    for app in "''${apps[@]}"; do
      source="$HOME/Applications/Home Manager Apps/$app"
      target="$HOME/Applications/$app"
      if [ -e "$source" ]; then
        if [ -L "$target" ] || [ -e "$target" ]; then rm -rf "$target"; fi
        ln -sf "$source" "$target"
        echo "  Linked $app"
      fi
    done
    echo "✅ macOS GUI applications linked"
  '';

  # ============================================================================
  # Nano Configuration
  # ============================================================================
  home.file.".nanorc".text = ''
    include ${pkgs.nano}/share/nano/*.nanorc
    set autoindent
    set tabstospaces
    set tabsize 2
    set linenumbers
    set mouse
    set constantshow
  '';

  # ============================================================================
  # Scripts Directory (Optional)
  # ============================================================================
  # Uncomment to link custom scripts from ./scripts/host-user/
  # home.file."Scripts" = {
  #   source = ./scripts/host-user;
  #   recursive = true;
  # };

  # ============================================================================
  # Additional Settings
  # ============================================================================
  xdg.enable = true;

  home.sessionVariables = {
    EDITOR = "nano";
  };
}
