[project]
name = "pharos"
revision = "1.0"

[profiles.csb0]
PHAROS_BEACON_CSB0_TOKEN = { description = "Pharos beacon token for csb0", required = true }

[profiles.csb1]
PHAROS_BEACON_CSB1_TOKEN = { description = "Pharos beacon token for csb1", required = true }

[profiles.dsc0]
PHAROS_BEACON_DSC0_TOKEN = { description = "Pharos beacon token for dsc0", required = true }

[profiles.gpc0]
PHAROS_BEACON_GPC0_TOKEN = { description = "Pharos beacon token for gpc0", required = true }

[profiles.hsb0]
PHAROS_BEACON_HSB0_TOKEN = { description = "Pharos beacon token for hsb0", required = true }

[profiles.hsb1]
PHAROS_BEACON_HSB1_TOKEN = { description = "Pharos beacon token for hsb1", required = true }

[profiles.hsb8]
PHAROS_BEACON_HSB8_TOKEN = { description = "Pharos beacon token for hsb8", required = true }

[profiles.hsb9]
PHAROS_BEACON_HSB9_TOKEN = { description = "Pharos beacon token for hsb9", required = true }
