# SSH Fleet Config for NixOS (system-level)
# Manages /etc/ssh/ssh_config
{ ... }:
{
  # NixOS: Configure system-wide SSH client via /etc/ssh/ssh_config
  programs.ssh.extraConfig = ''
    # Fleet SSH Configuration - Auto LAN→Tailscale fallback
    # Generated by modules/shared/ssh-fleet-nixos.nix

    # Keep-alive disabled (prevents drops during long ops like nixos-rebuild)
    # ServerAliveInterval 0 is the default - omitted

    # NOTE: No GitHub/Git SSH keys here!
    # Each host has its own keys. Per-host Git SSH config belongs in
    # the host's configuration.nix or user SSH config (~/.ssh/config).

    Host traefik.barta.cm
      HostName traefik.barta.cm
      User mba

    # === HOME NETWORK HOSTS ===
    Host hsb0
      HostName 192.168.1.99
      User mba
      ProxyCommand sh -c 'if nc -z -w2 %h %p 2>/dev/null; then nc %h %p; else nc hsb0.ts.barta.cm %p; fi'

    Host hsb0-lan
      HostName 192.168.1.99
      User mba

    Host hsb0-ts
      HostName hsb0.ts.barta.cm
      User mba

    Host hsb0-markus
      HostName 192.168.1.99
      User markus
      ProxyCommand sh -c 'if nc -z -w2 %h %p 2>/dev/null; then nc %h %p; else nc hsb0.ts.barta.cm %p; fi'

    Host hsb0-markus-lan
      HostName hsb0.lan
      User markus

    Host hsb0-markus-ip
      HostName 192.168.1.99
      User markus

    Host hsb0-markus-ts
      HostName hsb0.ts.barta.cm
      User markus

    Host hsb1
      HostName 192.168.1.101
      User mba
      ProxyCommand sh -c 'if nc -z -w2 %h %p 2>/dev/null; then nc %h %p; else nc hsb1.ts.barta.cm %p; fi'

    Host hsb1-lan
      HostName 192.168.1.101
      User mba

    Host hsb1-ts
      HostName hsb1.ts.barta.cm
      User mba

    Host hsb1-markus
      HostName 192.168.1.101
      User markus
      ProxyCommand sh -c 'if nc -z -w2 %h %p 2>/dev/null; then nc %h %p; else nc hsb1.ts.barta.cm %p; fi'

    Host hsb1-markus-lan
      HostName hsb1.lan
      User markus

    Host hsb1-markus-ip
      HostName 192.168.1.101
      User markus

    Host hsb1-markus-ts
      HostName hsb1.ts.barta.cm
      User markus

    Host hsb2
      HostName 192.168.1.95
      User mba
      ProxyCommand sh -c 'if nc -z -w2 %h %p 2>/dev/null; then nc %h %p; else nc hsb2.ts.barta.cm %p; fi'

    Host hsb2-lan
      HostName 192.168.1.95
      User mba

    Host hsb2-ts
      HostName hsb2.ts.barta.cm
      User mba

    Host hsb8
      HostName 192.168.1.100
      User mba
      ProxyCommand sh -c 'if nc -z -w2 %h %p 2>/dev/null; then nc %h %p; else nc hsb8.ts.barta.cm %p; fi'

    Host hsb8-lan
      HostName 192.168.1.100
      User mba

    Host hsb8-ts
      HostName hsb8.ts.barta.cm
      User mba

    Host hsb8-markus
      HostName 192.168.1.100
      User markus
      ProxyCommand sh -c 'if nc -z -w2 %h %p 2>/dev/null; then nc %h %p; else nc hsb8.ts.barta.cm %p; fi'

    Host hsb8-markus-lan
      HostName hsb8.lan
      User markus

    Host hsb8-markus-ip
      HostName 192.168.1.100
      User markus

    Host hsb8-markus-ts
      HostName hsb8.ts.barta.cm
      User markus

    # hsb9 = parents-in-law (Mac mini Late 2009). LAN .200 is target; while at
    # jhw22 (.203) the TS fallback wins via the proxy command.
    Host hsb9
      HostName 192.168.1.200
      User mba
      ProxyCommand sh -c 'if nc -z -w2 %h %p 2>/dev/null; then nc %h %p; else nc hsb9.ts.barta.cm %p; fi'

    Host hsb9-lan
      HostName 192.168.1.200
      User mba

    Host hsb9-ts
      HostName hsb9.ts.barta.cm
      User mba

    Host hsb9-markus
      HostName 192.168.1.200
      User markus
      ProxyCommand sh -c 'if nc -z -w2 %h %p 2>/dev/null; then nc %h %p; else nc hsb9.ts.barta.cm %p; fi'

    Host hsb9-markus-lan
      HostName hsb9.lan
      User markus

    Host hsb9-markus-ip
      HostName 192.168.1.200
      User markus

    Host hsb9-markus-ts
      HostName hsb9.ts.barta.cm
      User markus

    Host gpc0
      HostName 192.168.1.154
      User mba
      ProxyCommand sh -c 'if nc -z -w2 %h %p 2>/dev/null; then nc %h %p; else nc gpc0.ts.barta.cm %p; fi'

    Host gpc0-lan
      HostName 192.168.1.154
      User mba

    Host gpc0-ts
      HostName gpc0.ts.barta.cm
      User mba

    Host gpc0-markus
      HostName 192.168.1.154
      User markus
      ProxyCommand sh -c 'if nc -z -w2 %h %p 2>/dev/null; then nc %h %p; else nc gpc0.ts.barta.cm %p; fi'

    Host gpc0-markus-lan
      HostName gpc0.lan
      User markus

    Host gpc0-markus-ip
      HostName 192.168.1.154
      User markus

    Host gpc0-markus-ts
      HostName gpc0.ts.barta.cm
      User markus

    # === PORTABLE/WORK HOSTS ===
    Host miniserver-bp
      HostName 10.17.1.40
      Port 2222
      User mba
      ProxyCommand sh -c 'if nc -z -w2 %h %p 2>/dev/null; then nc %h %p; else nc miniserver-bp.ts.barta.cm %p; fi'

    Host miniserver-bp-lan
      HostName 10.17.1.40
      Port 2222
      User mba

    Host miniserver-bp-ts
      HostName miniserver-bp.ts.barta.cm
      Port 2222
      User mba

    Host msbp
      HostName miniserver-bp.ts.barta.cm
      Port 2222
      User mba

    Host msbp-lan
      HostName 10.17.1.40
      Port 2222
      User mba

    Host msbp-ts
      HostName miniserver-bp.ts.barta.cm
      Port 2222
      User mba

    # === CLOUD HOSTS ===
    Host csb0
      HostName csb0.ts.barta.cm
      User mba
      Port 2222

    Host csb0-ts
      HostName csb0.ts.barta.cm
      User mba
      Port 2222

    Host csb0-markus
      HostName cs0.barta.cm
      User markus
      Port 2222

    Host csb0-markus-ip
      HostName 89.58.63.96
      User markus
      Port 2222

    Host csb0-markus-ts
      HostName csb0.ts.barta.cm
      User markus
      Port 2222

    Host csb1
      HostName csb1.ts.barta.cm
      User mba
      Port 2222

    Host csb1-ts
      HostName csb1.ts.barta.cm
      User mba
      Port 2222

    Host csb1-markus
      HostName cs1.barta.cm
      User markus
      Port 2222

    Host csb1-markus-ip
      HostName 152.53.64.166
      User markus
      Port 2222

    Host csb1-markus-ts
      HostName csb1.ts.barta.cm
      User markus
      Port 2222
  '';
}
