# SSH Fleet Config for NixOS (system-level)
# Manages /etc/ssh/ssh_config
{ ... }:
{
  # NixOS: Configure system-wide SSH client via /etc/ssh/ssh_config
  programs.ssh.extraConfig = ''
    # Fleet SSH Configuration - Auto LAN→Tailscale fallback
    # Generated by modules/shared/ssh-fleet-nixos.nix

    # Keep-alive disabled (prevents drops during long ops like nixos-rebuild)
    # ServerAliveInterval 0 is the default - omitted

    # === EXISTING MANUAL CONFIG ===
    Host github-bp
      HostName github.com
      User git
      IdentityFile ~/.ssh/id_ed25519_bytepoets

    Host github.com
      HostName github.com
      User git
      IdentityFile ~/.ssh/id_rsa

    Host traefik.barta.cm
      HostName traefik.barta.cm
      User mba

    # === HOME NETWORK HOSTS ===
    Host hsb0
      HostName 192.168.1.99
      User mba
      ProxyCommand sh -c 'nc -w2 %h %p || nc hsb0.ts.barta.cm %p'

    Host hsb0-lan
      HostName 192.168.1.99
      User mba

    Host hsb0-ts
      HostName hsb0.ts.barta.cm
      User mba

    Host hsb1
      HostName 192.168.1.101
      User mba
      ProxyCommand sh -c 'nc -w2 %h %p || nc hsb1.ts.barta.cm %p'

    Host hsb1-lan
      HostName 192.168.1.101
      User mba

    Host hsb1-ts
      HostName hsb1.ts.barta.cm
      User mba

    Host hsb2
      HostName 192.168.1.95
      User mba
      ProxyCommand sh -c 'nc -w2 %h %p || nc hsb2.ts.barta.cm %p'

    Host hsb2-lan
      HostName 192.168.1.95
      User mba

    Host hsb2-ts
      HostName hsb2.ts.barta.cm
      User mba

    Host hsb8
      HostName 192.168.1.100
      User mba
      ProxyCommand sh -c 'nc -w2 %h %p || nc hsb8.ts.barta.cm %p'

    Host hsb8-lan
      HostName 192.168.1.100
      User mba

    Host hsb8-ts
      HostName hsb8.ts.barta.cm
      User mba

    Host gpc0
      HostName 192.168.1.154
      User mba
      ProxyCommand sh -c 'nc -w2 %h %p || nc gpc0.ts.barta.cm %p'

    Host gpc0-lan
      HostName 192.168.1.154
      User mba

    Host gpc0-ts
      HostName gpc0.ts.barta.cm
      User mba

    Host imac0
      HostName 192.168.1.150
      User markus
      ProxyCommand sh -c 'nc -w2 %h %p || nc imac0.ts.barta.cm %p'

    Host imac0-lan
      HostName 192.168.1.150
      User markus

    Host imac0-ts
      HostName imac0.ts.barta.cm
      User markus

    # === PORTABLE/WORK HOSTS ===
    Host mba-mbp-work
      HostName 192.168.1.197
      User mba
      ProxyCommand sh -c 'nc -w2 %h %p || nc mba-mbp-work.ts.barta.cm %p'

    Host mba-mbp-work-lan
      HostName 192.168.1.197
      User mba

    Host mba-mbp-work-ts
      HostName mba-mbp-work.ts.barta.cm
      User mba

    Host mbpw
      HostName mba-mbp-work

    Host mbpw-lan
      HostName 192.168.1.197
      User mba

    Host mbpw-ts
      HostName mba-mbp-work.ts.barta.cm
      User mba

    Host mba-imac-work
      HostName 10.17.1.7
      User markus
      ProxyCommand sh -c 'nc -w2 %h %p || nc mba-imac-work.ts.barta.cm %p'

    Host mba-imac-work-lan
      HostName 10.17.1.7
      User markus

    Host mba-imac-work-ts
      HostName mba-imac-work.ts.barta.cm
      User markus

    Host imacw
      HostName mba-imac-work

    Host imacw-lan
      HostName 10.17.1.7
      User markus

    Host imacw-ts
      HostName mba-imac-work.ts.barta.cm
      User markus

    Host miniserver-bp
      HostName 10.17.1.40
      User mba
      ProxyCommand sh -c 'nc -w2 %h %p || nc miniserver-bp.ts.barta.cm %p'

    Host miniserver-bp-lan
      HostName 10.17.1.40
      User mba

    Host miniserver-bp-ts
      HostName miniserver-bp.ts.barta.cm
      User mba

    Host msbp
      HostName miniserver-bp

    Host msbp-lan
      HostName 10.17.1.40
      User mba

    Host msbp-ts
      HostName miniserver-bp.ts.barta.cm
      User mba

    # === CLOUD HOSTS ===
    Host csb0
      HostName csb0.ts.barta.cm
      User mba
      Port 2222

    Host csb0-ts
      HostName csb0.ts.barta.cm
      User mba
      Port 2222

    Host csb1
      HostName csb1.ts.barta.cm
      User mba
      Port 2222

    Host csb1-ts
      HostName csb1.ts.barta.cm
      User mba
      Port 2222
  '';
}
