# SSH Fleet Config for NixOS (system-level)
# Manages /etc/ssh/ssh_config
{ ... }:
{
  # NixOS: Configure system-wide SSH client via /etc/ssh/ssh_config
  programs.ssh.extraConfig = ''
    # Fleet SSH Configuration
    # Generated by modules/shared/ssh-fleet-nixos.nix
    #
    # MagicDNS is OFF by permanent decision (OPS-146) - *.ts.barta.cm resolves to
    # nothing. Home hosts are LAN-only here; cloud hosts use public DNS on :2222.
    # Off-LAN, address tailnet hosts by IP from `tailscale status` (not hardcoded).

    # Keep-alive disabled (prevents drops during long ops like nixos-rebuild)
    # ServerAliveInterval 0 is the default - omitted

    # NOTE: No GitHub/Git SSH keys here!
    # Each host has its own keys. Per-host Git SSH config belongs in
    # the host's configuration.nix or user SSH config (~/.ssh/config).

    Host traefik.barta.cm
      HostName traefik.barta.cm
      User mba

    # === HOME NETWORK HOSTS (LAN only; off-LAN use tailnet IP) ===
    Host hsb0
      HostName 192.168.1.99
      User mba

    Host hsb0-lan
      HostName 192.168.1.99
      User mba

    Host hsb0-markus
      HostName 192.168.1.99
      User markus

    Host hsb0-markus-lan
      HostName hsb0.lan
      User markus

    Host hsb0-markus-ip
      HostName 192.168.1.99
      User markus

    Host hsb1
      HostName 192.168.1.101
      User mba

    Host hsb1-lan
      HostName 192.168.1.101
      User mba

    Host hsb1-markus
      HostName 192.168.1.101
      User markus

    Host hsb1-markus-lan
      HostName hsb1.lan
      User markus

    Host hsb1-markus-ip
      HostName 192.168.1.101
      User markus

    Host hsb2
      HostName 192.168.1.95
      User mba

    Host hsb2-lan
      HostName 192.168.1.95
      User mba

    Host hsb8
      HostName 192.168.1.100
      User mba

    Host hsb8-lan
      HostName 192.168.1.100
      User mba

    Host hsb8-markus
      HostName 192.168.1.100
      User markus

    Host hsb8-markus-lan
      HostName hsb8.lan
      User markus

    Host hsb8-markus-ip
      HostName 192.168.1.100
      User markus

    # hsb9 = parents-in-law (Mac mini Late 2009). LAN .200 is target; while at
    # jhw22 (.203) the TS fallback wins via the proxy command.
    Host hsb9
      HostName 192.168.1.200
      User mba

    Host hsb9-lan
      HostName 192.168.1.200
      User mba

    Host hsb9-markus
      HostName 192.168.1.200
      User markus

    Host hsb9-markus-lan
      HostName hsb9.lan
      User markus

    Host hsb9-markus-ip
      HostName 192.168.1.200
      User markus

    # === CLOUD HOSTS ===
    Host csb0
      HostName cs0.barta.cm
      User mba
      Port 2222

    Host csb0-markus
      HostName cs0.barta.cm
      User markus
      Port 2222

    Host csb0-markus-ip
      HostName 89.58.63.96
      User markus
      Port 2222

    Host csb1
      HostName cs1.barta.cm
      User mba
      Port 2222

    Host csb1-markus
      HostName cs1.barta.cm
      User markus
      Port 2222

    Host csb1-markus-ip
      HostName 152.53.64.166
      User markus
      Port 2222
  '';
}
