# ╔══════════════════════════════════════════════════════════════════════════════╗
# ║                    THEME MODULE - Home Manager Integration                   ║
# ╚══════════════════════════════════════════════════════════════════════════════╝
#
# This module auto-detects the hostname and applies the corresponding theme
# palette to starship, zellij, and eza. It follows the DRY principle - define
# colors once in theme-palettes.nix, use everywhere.
#
# ════════════════════════════════════════════════════════════════════════════════
# CATPPUCCIN OVERRIDE (Tokyo Night)
# ════════════════════════════════════════════════════════════════════════════════
#
# The external hokage module includes Catppuccin theming, but we use Tokyo Night.
# This module OVERRIDES hokage's starship theming by writing our own config to
# ~/.config/starship.toml with per-host gradient colors.
#
# When pbek adds `hokage.catppuccin.enable = false`, we can remove the catppuccin
# dependency from flake.nix. See modules/shared/README.md for full details.
#
# ════════════════════════════════════════════════════════════════════════════════
#
# CRITICAL: Starship config uses a TEMPLATE FILE to preserve Unicode characters.
# See modules/shared/README.md for details on why this is necessary.
#
# Usage in home.nix:
#   imports = [ ../../modules/shared/theme-hm.nix ];
#
# That's it! The module will:
#   1. Detect hostname automatically
#   2. Look up the palette from theme-palettes.nix
#   3. Generate themed configs for starship, zellij, and eza
#
# To override the auto-detected hostname:
#   theme.hostname = "hsb0";
#
{
  config,
  lib,
  pkgs,
  hostname ? null, # Passed from flake.nix extraSpecialArgs (pure, reliable)
  ...
}:

let
  # Resolve hostname from extraSpecialArgs or environment (before module system)
  detectedHostname =
    if hostname != null then
      hostname
    else
      let
        envHost = builtins.getEnv "HOST";
      in
      if envHost != "" then envHost else "unknown";
in

let
  # Import the palette definitions
  themePalettes = import ./theme-palettes.nix;

  # Get the configured or auto-detected hostname (renamed to avoid shadowing)
  resolvedHostname = config.theme.hostname;

  # Look up the palette for this host (fallback to default)
  paletteName = themePalettes.hostPalette.${resolvedHostname} or themePalettes.defaultPalette;
  palette = themePalettes.palettes.${paletteName};

  # Status colors (universal across all palettes)
  status = themePalettes.statusColors;

  # ════════════════════════════════════════════════════════════════════════════
  # STARSHIP CONFIG GENERATOR (Template-based to preserve Unicode)
  # ════════════════════════════════════════════════════════════════════════════

  # Read the template file (contains all Unicode characters intact)
  starshipTemplate = builtins.readFile ./starship-template.toml;

  # Build the starship config by substituting ONLY color placeholders (ASCII-safe)
  mkStarshipConfig =
    p:
    let
      g = p.gradient;
      t = p.text;
    in
    builtins.replaceStrings
      [
        # Header placeholders
        "__HOSTNAME__"
        "__PALETTE_NAME__"
        "__PALETTE_KEY__"
        "__CATEGORY__"

        # Gradient colors (lightest to darkest)
        "__LIGHTEST__"
        "__PRIMARY__"
        "__SECONDARY__"
        "__MIDDARK__"
        "__DARK__"
        "__DARKER__"
        "__DARKEST__"

        # Text colors
        "__TEXT_ON_LIGHTEST__"
        "__TEXT_ON_MEDIUM__"
        "__TEXT_ON_SECONDARY__"
        "__TEXT_ACCENT__"
        "__TEXT_MUTED__"
        "__TEXT_MUTED_LIGHT__"

        # Status colors (universal)
        "__ROOT_BG__"
        "__ROOT_FG__"
        "__ERROR_BG__"
        "__ERROR_FG__"
        "__SUDO_FG__"
      ]
      [
        # Header values
        resolvedHostname
        p.name
        paletteName
        p.category

        # Gradient colors
        g.lightest
        g.primary
        g.secondary
        g.midDark
        g.dark
        g.darker
        g.darkest

        # Text colors
        t.onLightest
        t.onMedium
        (t.onSecondary or t.onMedium)
        t.accent
        t.muted
        t.mutedLight

        # Status colors
        status.root.bg
        status.root.fg
        status.error.bg
        status.error.fg
        status.sudo.fg
      ]
      starshipTemplate;

  # ════════════════════════════════════════════════════════════════════════════
  # ZELLIJ CONFIG GENERATOR (No special Unicode, can use Nix strings)
  # ════════════════════════════════════════════════════════════════════════════

  mkZellijConfig =
    p: hn:
    let
      z = p.zellij;
    in
    ''
      // ╔══════════════════════════════════════════════════════════════════════════════╗
      // ║                      ZELLIJ CONFIG - ${hn} (${p.name})
      // ╚══════════════════════════════════════════════════════════════════════════════╝
      //
      // Theme: ${paletteName} (${p.category})
      // Auto-generated by: modules/shared/theme-hm.nix
      //

      default_shell "fish"
      show_startup_tips false

      // ════════════════════════════════════════════════════════════════════════════════
      // KEYBINDINGS
      // ════════════════════════════════════════════════════════════════════════════════

      keybinds {
          unbind "Ctrl o"
          normal {
              bind "Ctrl a" { MoveTab "Left"; }
              bind "Ctrl e" { SwitchToMode "Session"; }
          }
          session {
              bind "Ctrl e" { SwitchToMode "Normal"; }
          }
          tab {
              bind "c" {
                  NewTab {
                      cwd "~"
                  }
                  SwitchToMode "normal";
              }
          }
      }

      // ════════════════════════════════════════════════════════════════════════════════
      // THEME DEFINITION
      // ════════════════════════════════════════════════════════════════════════════════

      themes {
          ${hn} {
              bg "${z.bg}"
              fg "${z.fg}"
              red "${z.keybindFg or themePalettes.statusColors.root.bg}"
              green "${z.highlight}"
              blue "${p.gradient.primary}"
              yellow "${themePalettes.statusColors.sudo.fg}"
              magenta "${p.gradient.secondary}"
              orange "${themePalettes.statusColors.error.bg}"
              cyan "${p.gradient.lightest}"
              black "${z.black}"
              white "${z.white}"
          }
      }

      // ════════════════════════════════════════════════════════════════════════════════
      // SESSION & THEME
      // ════════════════════════════════════════════════════════════════════════════════

      session_serialization true
      theme "${hn}"
    '';

in
{
  # ════════════════════════════════════════════════════════════════════════════
  # MODULE OPTIONS
  # ════════════════════════════════════════════════════════════════════════════

  options.theme = {
    enable = lib.mkEnableOption "per-host theming for starship, zellij, and eza" // {
      default = true;
    };

    hostname = lib.mkOption {
      type = lib.types.str;
      default = detectedHostname;
      description = ''
        Hostname for theme lookup. Detection priority:
        1. Explicit `theme.hostname = "myhost";` in config
        2. `hostname` passed via flake.nix extraSpecialArgs (recommended)
        3. $HOST environment variable (impure, may not work in flakes)
      '';
    };

    starship.enable = lib.mkEnableOption "themed starship prompt" // {
      default = true;
    };

    zellij.enable = lib.mkEnableOption "themed zellij config" // {
      default = true;
    };

    eza.enable = lib.mkEnableOption "themed eza colors" // {
      default = true;
    };

    # Expose the detected palette for debugging/reference
    palette = lib.mkOption {
      type = lib.types.attrs;
      default = palette;
      readOnly = true;
      description = "The resolved palette for this host (read-only)";
    };

    paletteName = lib.mkOption {
      type = lib.types.str;
      default = paletteName;
      readOnly = true;
      description = "The name of the resolved palette (read-only)";
    };
  };

  # ════════════════════════════════════════════════════════════════════════════
  # MODULE CONFIGURATION
  # ════════════════════════════════════════════════════════════════════════════

  config = lib.mkIf config.theme.enable {
    # Starship config (generated from TEMPLATE to preserve Unicode)
    home.file.".config/starship.toml" = lib.mkIf config.theme.starship.enable {
      force = true; # Defensive: ensure Tokyo Night wins over any hokage config
      text = mkStarshipConfig palette;
    };

    # Zellij config (generated from palette)
    # Create the ENTIRE .config/zellij directory to override hokage's
    # Must use mkForce on source to win the conflict with hokage's home.file
    home.file.".config/zellij" = lib.mkIf config.theme.zellij.enable {
      source = lib.mkForce (pkgs.writeTextDir "config.kdl" (mkZellijConfig palette resolvedHostname));
      recursive = true;
      force = true;
    };

    # Eza theme file (Tokyo Night based, sysop-focused)
    # Using theme file instead of EZA_COLORS for better maintainability
    home.file.".config/eza/theme.yml" = lib.mkIf config.theme.eza.enable {
      source = ./eza-themes/sysop.yml;
    };

    # Eza needs EZA_CONFIG_DIR to find the theme file
    home.sessionVariables = lib.mkIf config.theme.eza.enable {
      EZA_CONFIG_DIR = "$HOME/.config/eza";
      LS_COLORS = "di=1;34:ln=36:ex=1;32:or=31";
    };

    # Fish-specific: eza config dir and LS_COLORS (fish doesn't source bash profiles)
    programs.fish.interactiveShellInit = lib.mkIf config.theme.eza.enable ''
      # Tell eza where to find theme.yml
      set -gx EZA_CONFIG_DIR "$HOME/.config/eza"
      # LS_COLORS for basic ls compatibility
      set -gx LS_COLORS "di=1;34:ln=36:ex=1;32:or=31"
    '';

    # ══════════════════════════════════════════════════════════════════════════
    # CATPPUCCIN OVERRIDES - Tokyo Night for apps that catppuccin would theme
    # ══════════════════════════════════════════════════════════════════════════
    # These explicit settings override hokage's catppuccin theming.
    # When hokage.catppuccin.enable = false becomes available, these can be removed
    # (the apps will just use their defaults or our explicit Tokyo Night settings).
    # ══════════════════════════════════════════════════════════════════════════

    # bat: Use Tokyo Night theme (built-in)
    programs.bat = {
      config = {
        theme = "tokyonight_night";
      };
    };

    # fzf: Tokyo Night colors
    programs.fzf = {
      colors = {
        fg = "#c0caf5";
        bg = "#1a1b26";
        hl = "#bb9af7";
        "fg+" = "#c0caf5";
        "bg+" = "#292e42";
        "hl+" = "#7dcfff";
        info = "#7aa2f7";
        prompt = "#7dcfff";
        pointer = "#7dcfff";
        marker = "#9ece6a";
        spinner = "#9ece6a";
        header = "#9ece6a";
      };
    };

    # lazygit: Tokyo Night theme
    home.file.".config/lazygit/config.yml" = {
      force = true; # Overwrite existing config
      text = ''
        gui:
          theme:
            activeBorderColor:
              - "#7aa2f7"
              - bold
            inactiveBorderColor:
              - "#565f89"
            searchingActiveBorderColor:
              - "#7aa2f7"
              - bold
            optionsTextColor:
              - "#7aa2f7"
            selectedLineBgColor:
              - "#292e42"
            cherryPickedCommitFgColor:
              - "#7aa2f7"
            cherryPickedCommitBgColor:
              - "#bb9af7"
            markedBaseCommitFgColor:
              - "#7aa2f7"
            markedBaseCommitBgColor:
              - "#e0af68"
            unstagedChangesColor:
              - "#db4b4b"
            defaultFgColor:
              - "#c0caf5"
      '';
    };

    # Note: fish syntax highlighting still uses catppuccin on NixOS (no easy override)
    # When hokage.catppuccin.enable = false is available, this will be resolved.
  };
}
