# ╔══════════════════════════════════════════════════════════════════════════════╗
# ║                    THEME MODULE - Home Manager Integration                   ║
# ╚══════════════════════════════════════════════════════════════════════════════╝
#
# This module auto-detects the hostname and applies the corresponding theme
# palette to starship, zellij, and eza. It follows the DRY principle - define
# colors once in theme-palettes.nix, use everywhere.
#
# Usage in home.nix:
#   imports = [ ../../modules/shared/theme-hm.nix ];
#
# That's it! The module will:
#   1. Detect hostname automatically
#   2. Look up the palette from theme-palettes.nix
#   3. Generate themed configs for starship, zellij, and eza
#
# To override the auto-detected hostname:
#   theme.hostname = "hsb0";
#
{
  config,
  lib,
  ...
}:

let
  # Import the palette definitions
  themePalettes = import ./theme-palettes.nix;

  # Get the configured or auto-detected hostname
  hostname = config.theme.hostname;

  # Look up the palette for this host (fallback to default)
  paletteName = themePalettes.hostPalette.${hostname} or themePalettes.defaultPalette;
  palette = themePalettes.palettes.${paletteName};

  # Status colors (universal across all palettes)
  status = themePalettes.statusColors;

  # ════════════════════════════════════════════════════════════════════════════
  # STARSHIP CONFIG GENERATOR
  # ════════════════════════════════════════════════════════════════════════════

  mkStarshipConfig =
    p:
    let
      g = p.gradient;
      t = p.text;
    in
    ''
      # ╔══════════════════════════════════════════════════════════════════════════════╗
      # ║                     STARSHIP PROMPT - ${hostname} (${p.name})
      # ╚══════════════════════════════════════════════════════════════════════════════╝
      #
      # Theme: ${paletteName} (${p.category})
      # Auto-generated by: modules/shared/theme-hm.nix
      #
      # Features:
      #   - Powerline gradient (${p.name} spectrum)
      #   - Root alert (red warning segment)
      #   - Exit status badge (on error)
      #   - Sudo cached indicator
      #   - Command duration (> 2s)
      #   - Background jobs indicator
      #   - Success/error character prompt
      #

      "$schema" = 'https://starship.rs/config-schema.json'

      # ════════════════════════════════════════════════════════════════════════════════
      # PROMPT FORMAT
      # ════════════════════════════════════════════════════════════════════════════════

      format = """
      ''${custom.root_alert}\
      [░▒▓](${g.lightest})\
      $os\
      [](bg:${g.primary} fg:${g.lightest})\
      $directory\
      [](fg:${g.primary} bg:${g.secondary})\
      $username\
      $hostname\
      [](fg:${g.secondary} bg:${g.midDark})\
      $jobs\
      $git_branch\
      $git_status\
      ''${custom.gitcount}\
      [](fg:${g.midDark} bg:${g.dark})\
      $nodejs\
      $python\
      $rust\
      $golang\
      $php\
      $docker_context\
      [](fg:${g.dark})\
      $fill\
      $status\
      $cmd_duration\
      [](fg:${g.darker})\
      $time\
      [](fg:${g.darker} bg:${g.darkest})\
      $sudo\
      $nix_shell\
      [](fg:${g.darkest})\
      \n$character"""

      # ════════════════════════════════════════════════════════════════════════════════
      # ROOT ALERT - Danger segment (only when root)
      # ════════════════════════════════════════════════════════════════════════════════

      [custom.root_alert]
      command = "echo '⚠'"
      when = "test $USER = root"
      style = "bold fg:${status.root.fg} bg:${status.root.bg}"
      format = "[$output ]($style)"

      # ════════════════════════════════════════════════════════════════════════════════
      # OS ICON
      # ════════════════════════════════════════════════════════════════════════════════

      [os]
      disabled = false
      style = "bg:${g.lightest} fg:${t.onLightest}"
      format = "[ $symbol ]($style)"

      [os.symbols]
      Macos = ""
      NixOS = ""
      Linux = ""

      # ════════════════════════════════════════════════════════════════════════════════
      # DIRECTORY
      # ════════════════════════════════════════════════════════════════════════════════

      [directory]
      style = "fg:${t.onMedium} bg:${g.primary}"
      format = "[ $path ]($style)"
      truncation_length = 0
      truncate_to_repo = false
      truncation_symbol = "…/"

      [directory.substitutions]
      "Documents" = "󰈙 "
      "Downloads" = " "
      "Music" = " "
      "Pictures" = " "

      # ════════════════════════════════════════════════════════════════════════════════
      # USERNAME & HOSTNAME
      # ════════════════════════════════════════════════════════════════════════════════

      [username]
      show_always = true
      style_user = "fg:${t.onMedium} bg:${g.secondary}"
      style_root = "fg:${status.root.bg} bg:${g.secondary}"
      format = '[ $user]($style)'

      [hostname]
      ssh_only = false
      style = "fg:${t.onMedium} bg:${g.secondary}"
      format = '[@$hostname ]($style)'

      # ════════════════════════════════════════════════════════════════════════════════
      # JOBS (Background processes)
      # ════════════════════════════════════════════════════════════════════════════════

      [jobs]
      symbol = "✦"
      style = "fg:${t.accent} bg:${g.midDark}"
      number_threshold = 1
      format = '[[ $symbol$number ](fg:${t.accent} bg:${g.midDark})]($style)'

      # ════════════════════════════════════════════════════════════════════════════════
      # GIT
      # ════════════════════════════════════════════════════════════════════════════════

      [git_branch]
      symbol = ""
      style = "bg:${g.midDark}"
      format = '[[ $symbol $branch ](fg:${t.accent} bg:${g.midDark})]($style)'

      [git_status]
      style = "bg:${g.midDark}"
      format = '[[($all_status$ahead_behind )](fg:${t.accent} bg:${g.midDark})]($style)'

      [custom.gitcount]
      command = "git rev-list --count HEAD 2>/dev/null"
      when = "git rev-parse --is-inside-work-tree 2>/dev/null"
      style = "bg:${g.midDark}"
      format = "[[#$output ](fg:${t.muted} bg:${g.midDark})]($style)"

      # ════════════════════════════════════════════════════════════════════════════════
      # LANGUAGES
      # ════════════════════════════════════════════════════════════════════════════════

      [nodejs]
      symbol = ""
      style = "bg:${g.dark}"
      format = '[[ $symbol ($version) ](fg:${t.accent} bg:${g.dark})]($style)'

      [python]
      symbol = ""
      style = "bg:${g.dark}"
      format = '[[ $symbol ($version) ](fg:${t.accent} bg:${g.dark})]($style)'

      [rust]
      symbol = ""
      style = "bg:${g.dark}"
      format = '[[ $symbol ($version) ](fg:${t.accent} bg:${g.dark})]($style)'

      [golang]
      symbol = ""
      style = "bg:${g.dark}"
      format = '[[ $symbol ($version) ](fg:${t.accent} bg:${g.dark})]($style)'

      [php]
      symbol = ""
      style = "bg:${g.dark}"
      format = '[[ $symbol ($version) ](fg:${t.accent} bg:${g.dark})]($style)'

      [docker_context]
      symbol = ""
      style = "bg:${g.dark}"
      format = '[[ $symbol $context ](fg:${t.accent} bg:${g.dark})]($style)'
      only_with_files = true

      # ════════════════════════════════════════════════════════════════════════════════
      # FILL (flexible space between left and right)
      # ════════════════════════════════════════════════════════════════════════════════

      [fill]
      symbol = " "

      # ════════════════════════════════════════════════════════════════════════════════
      # STATUS (Exit code on error)
      # ════════════════════════════════════════════════════════════════════════════════

      [status]
      disabled = false
      style = "bold fg:${status.error.fg} bg:${status.error.bg}"
      symbol = "✘"
      format = '[ $symbol $status ]($style)'

      # ════════════════════════════════════════════════════════════════════════════════
      # COMMAND DURATION (> 2 seconds)
      # ════════════════════════════════════════════════════════════════════════════════

      [cmd_duration]
      min_time = 2000
      style = "fg:${t.mutedLight}"
      format = '[ ⏱ $duration]($style)'

      # ════════════════════════════════════════════════════════════════════════════════
      # TIME
      # ════════════════════════════════════════════════════════════════════════════════

      [time]
      disabled = false
      time_format = "%T"
      style = "bg:${g.darker}"
      format = '[[  $time ](fg:${t.mutedLight} bg:${g.darker})]($style)'

      # ════════════════════════════════════════════════════════════════════════════════
      # SUDO (cached credentials)
      # ════════════════════════════════════════════════════════════════════════════════

      [sudo]
      disabled = false
      style = "fg:${status.sudo.fg} bg:${g.darkest}"
      symbol = " "
      format = '[[$symbol](fg:${status.sudo.fg} bg:${g.darkest})]($style)'

      # ════════════════════════════════════════════════════════════════════════════════
      # NIX SHELL
      # ════════════════════════════════════════════════════════════════════════════════

      [nix_shell]
      symbol = ""
      style = "bg:${g.darkest}"
      format = '[[ $symbol $state ](fg:${t.muted} bg:${g.darkest})]($style)'

      # ════════════════════════════════════════════════════════════════════════════════
      # CHARACTER (Prompt on new line)
      # ════════════════════════════════════════════════════════════════════════════════

      [character]
      success_symbol = "[❯](bold fg:${t.accent})"
      error_symbol = "[✗](bold fg:${status.error.bg})"
    '';

  # ════════════════════════════════════════════════════════════════════════════
  # ZELLIJ CONFIG GENERATOR
  # ════════════════════════════════════════════════════════════════════════════

  mkZellijConfig =
    p: hn:
    let
      z = p.zellij;
    in
    ''
      // ╔══════════════════════════════════════════════════════════════════════════════╗
      // ║                      ZELLIJ CONFIG - ${hn} (${p.name})
      // ╚══════════════════════════════════════════════════════════════════════════════╝
      //
      // Theme: ${paletteName} (${p.category})
      // Auto-generated by: modules/shared/theme-hm.nix
      //

      default_shell "fish"

      // ════════════════════════════════════════════════════════════════════════════════
      // KEYBINDINGS
      // ════════════════════════════════════════════════════════════════════════════════

      keybinds {
          unbind "Ctrl o"
          normal {
              bind "Ctrl a" { MoveTab "Left"; }
              bind "Ctrl e" { SwitchToMode "Session"; }
          }
          session {
              bind "Ctrl e" { SwitchToMode "Normal"; }
          }
          tab {
              bind "c" {
                  NewTab {
                      cwd "~"
                  }
                  SwitchToMode "normal";
              }
          }
      }

      // ════════════════════════════════════════════════════════════════════════════════
      // THEME DEFINITION
      // ════════════════════════════════════════════════════════════════════════════════

      themes {
          ${hn} {
              bg "${z.bg}"
              fg "${z.fg}"
              red "${themePalettes.statusColors.root.bg}"
              green "${z.highlight}"
              blue "${p.gradient.primary}"
              yellow "${themePalettes.statusColors.sudo.fg}"
              magenta "${p.gradient.secondary}"
              orange "${themePalettes.statusColors.error.bg}"
              cyan "${p.gradient.lightest}"
              black "${z.black}"
              white "${z.white}"
          }
      }

      // ════════════════════════════════════════════════════════════════════════════════
      // SESSION & THEME
      // ════════════════════════════════════════════════════════════════════════════════

      session_serialization true
      theme "${hn}"
    '';

  # ════════════════════════════════════════════════════════════════════════════
  # EZA COLORS GENERATOR
  # ════════════════════════════════════════════════════════════════════════════

  # Simpler approach - just set directory style

in
{
  # ════════════════════════════════════════════════════════════════════════════
  # MODULE OPTIONS
  # ════════════════════════════════════════════════════════════════════════════

  options.theme = {
    enable = lib.mkEnableOption "per-host theming for starship, zellij, and eza" // {
      default = true;
    };

    hostname = lib.mkOption {
      type = lib.types.str;
      default = builtins.getEnv "HOST";
      description = "Hostname for theme lookup. Auto-detected from $HOST if not set.";
    };

    starship.enable = lib.mkEnableOption "themed starship prompt" // {
      default = true;
    };

    zellij.enable = lib.mkEnableOption "themed zellij config" // {
      default = true;
    };

    eza.enable = lib.mkEnableOption "themed eza colors" // {
      default = true;
    };

    # Expose the detected palette for debugging/reference
    palette = lib.mkOption {
      type = lib.types.attrs;
      default = palette;
      readOnly = true;
      description = "The resolved palette for this host (read-only)";
    };

    paletteName = lib.mkOption {
      type = lib.types.str;
      default = paletteName;
      readOnly = true;
      description = "The name of the resolved palette (read-only)";
    };
  };

  # ════════════════════════════════════════════════════════════════════════════
  # MODULE CONFIGURATION
  # ════════════════════════════════════════════════════════════════════════════

  config = lib.mkIf config.theme.enable {
    # Starship config (generated from palette)
    home.file.".config/starship.toml" = lib.mkIf config.theme.starship.enable {
      text = mkStarshipConfig palette;
    };

    # Zellij config (generated from palette)
    home.file.".config/zellij/config.kdl" = lib.mkIf config.theme.zellij.enable {
      text = mkZellijConfig palette hostname;
    };

    # EZA colors via session variable
    home.sessionVariables = lib.mkIf config.theme.eza.enable {
      # Use bold blue for directories (works universally)
      # More sophisticated color mapping can be added later
      EZA_COLORS = "di=1;34";
      # Also set LS_COLORS for compatibility
      LS_COLORS = "di=1;34";
    };
  };
}
