#!/usr/bin/env bash
# ╔══════════════════════════════════════════════════════════════════════════════╗
# ║                    T01 - Theme Module Automated Tests                        ║
# ╚══════════════════════════════════════════════════════════════════════════════╝
#
# Host: imac0
# Theme: lightGray (Workstation - Home)
# Tests: Starship, Zellij, Eza configuration verification
#
# Usage: ./T01-theme.sh
#

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Counters
PASSED=0
FAILED=0
TOTAL=0

# ════════════════════════════════════════════════════════════════════════════════
# Helper Functions
# ════════════════════════════════════════════════════════════════════════════════

print_header() {
  echo ""
  echo -e "${BLUE}════════════════════════════════════════════════════════════════${NC}"
  echo -e "${BLUE}  $1${NC}"
  echo -e "${BLUE}════════════════════════════════════════════════════════════════${NC}"
}

print_test() {
  echo -e "\n${YELLOW}▶ $1${NC}"
  ((TOTAL++)) || true
}

pass() {
  echo -e "${GREEN}  ✅ PASS: $1${NC}"
  ((PASSED++)) || true
}

fail() {
  echo -e "${RED}  ❌ FAIL: $1${NC}"
  ((FAILED++)) || true
}

check_file_exists() {
  if [[ -f "$1" ]]; then
    pass "File exists: $1"
    return 0
  else
    fail "File missing: $1"
    return 1
  fi
}

check_file_contains() {
  local file="$1"
  local pattern="$2"
  local description="$3"

  if grep -q "$pattern" "$file" 2>/dev/null; then
    pass "$description"
    return 0
  else
    fail "$description (pattern not found: $pattern)"
    return 1
  fi
}

# ════════════════════════════════════════════════════════════════════════════════
# Test Suite
# ════════════════════════════════════════════════════════════════════════════════

print_header "T01 - Theme Module Tests (imac0 / lightGray)"

echo "Host: $(hostname)"
echo "Date: $(date)"

# ────────────────────────────────────────────────────────────────────────────────
# T01.1 - Starship Configuration File
# ────────────────────────────────────────────────────────────────────────────────

print_test "T01.1 - Starship Configuration"

check_file_exists "$HOME/.config/starship.toml"
check_file_contains "$HOME/.config/starship.toml" "imac0" "Starship config mentions hostname 'imac0'"
check_file_contains "$HOME/.config/starship.toml" "Light Gray" "Starship config mentions 'Light Gray' theme"
check_file_contains "$HOME/.config/starship.toml" "theme-hm.nix" "Starship config auto-generated by theme-hm.nix"
check_file_contains "$HOME/.config/starship.toml" "lightGray" "Starship config uses lightGray palette"

# ────────────────────────────────────────────────────────────────────────────────
# T01.2 - Starship Features
# ────────────────────────────────────────────────────────────────────────────────

print_test "T01.2 - Starship Features"

check_file_contains "$HOME/.config/starship.toml" "custom.root_alert" "Root alert segment configured"
check_file_contains "$HOME/.config/starship.toml" '\[status\]' "Exit status module configured"
check_file_contains "$HOME/.config/starship.toml" '\[sudo\]' "Sudo indicator configured"
check_file_contains "$HOME/.config/starship.toml" '\[cmd_duration\]' "Command duration configured"
check_file_contains "$HOME/.config/starship.toml" '\[jobs\]' "Background jobs configured"

# ────────────────────────────────────────────────────────────────────────────────
# T01.3 - Starship Color Values (lightGray palette)
# ────────────────────────────────────────────────────────────────────────────────

print_test "T01.3 - Starship Colors (lightGray palette)"

# These are the lightGray gradient colors from theme-palettes.nix
check_file_contains "$HOME/.config/starship.toml" "#e0e2e8" "Lightest gradient color present"
check_file_contains "$HOME/.config/starship.toml" "#a8aeb8" "Primary gradient color present"
check_file_contains "$HOME/.config/starship.toml" "#888e98" "Secondary gradient color present"
check_file_contains "$HOME/.config/starship.toml" "#181a1c" "Darkest gradient color present"

# ────────────────────────────────────────────────────────────────────────────────
# T01.4 - Zellij Configuration File
# ────────────────────────────────────────────────────────────────────────────────

print_test "T01.4 - Zellij Configuration"

check_file_exists "$HOME/.config/zellij/config.kdl"
check_file_contains "$HOME/.config/zellij/config.kdl" "imac0" "Zellij config mentions hostname 'imac0'"
check_file_contains "$HOME/.config/zellij/config.kdl" "Light Gray" "Zellij config mentions 'Light Gray' theme"
check_file_contains "$HOME/.config/zellij/config.kdl" "theme-hm.nix" "Zellij config auto-generated by theme-hm.nix"

# ────────────────────────────────────────────────────────────────────────────────
# T01.5 - Zellij Theme Definition
# ────────────────────────────────────────────────────────────────────────────────

print_test "T01.5 - Zellij Theme"

check_file_contains "$HOME/.config/zellij/config.kdl" 'theme "imac0"' "Zellij uses hostname as theme name"
check_file_contains "$HOME/.config/zellij/config.kdl" "imac0 {" "Zellij theme block defined for imac0"
check_file_contains "$HOME/.config/zellij/config.kdl" 'default_shell "fish"' "Zellij default shell is fish"

# ────────────────────────────────────────────────────────────────────────────────
# T01.6 - Zellij Keybindings
# ────────────────────────────────────────────────────────────────────────────────

print_test "T01.6 - Zellij Keybindings"

check_file_contains "$HOME/.config/zellij/config.kdl" 'bind "Ctrl e"' "Ctrl+e keybinding configured"
check_file_contains "$HOME/.config/zellij/config.kdl" 'unbind "Ctrl o"' "Ctrl+o unbound"
check_file_contains "$HOME/.config/zellij/config.kdl" 'bind "Ctrl a"' "Ctrl+a keybinding configured"

# ────────────────────────────────────────────────────────────────────────────────
# T01.7 - Eza Colors Environment Variable
# ────────────────────────────────────────────────────────────────────────────────

print_test "T01.7 - Eza Colors"

# Check session variables file
HM_SESSION_VARS="$HOME/.nix-profile/etc/profile.d/hm-session-vars.sh"
if [[ -f "$HM_SESSION_VARS" ]]; then
  check_file_contains "$HM_SESSION_VARS" "EZA_COLORS" "EZA_COLORS in session vars"
  check_file_contains "$HM_SESSION_VARS" "LS_COLORS" "LS_COLORS in session vars"
else
  fail "Session vars file not found: $HM_SESSION_VARS"
fi

# ────────────────────────────────────────────────────────────────────────────────
# T01.8 - Theme Module Integration
# ────────────────────────────────────────────────────────────────────────────────

print_test "T01.8 - Theme Module Integration"

# Check that all three configs have consistent theme info
if grep -q "lightGray" "$HOME/.config/starship.toml" &&
  grep -q "lightGray" "$HOME/.config/zellij/config.kdl"; then
  pass "All configs use consistent lightGray palette"
else
  fail "Palette inconsistency between configs"
fi

if grep -q "theme-hm.nix" "$HOME/.config/starship.toml" &&
  grep -q "theme-hm.nix" "$HOME/.config/zellij/config.kdl"; then
  pass "All configs generated by theme-hm.nix"
else
  fail "Not all configs generated by theme-hm.nix"
fi

# ════════════════════════════════════════════════════════════════════════════════
# Summary
# ════════════════════════════════════════════════════════════════════════════════

print_header "Test Summary"

echo ""
echo -e "  Total:  ${TOTAL}"
echo -e "  ${GREEN}Passed: ${PASSED}${NC}"
echo -e "  ${RED}Failed: ${FAILED}${NC}"
echo ""

if [[ $FAILED -eq 0 ]]; then
  echo -e "${GREEN}═══════════════════════════════════════════════════════════════════${NC}"
  echo -e "${GREEN}  ✅ ALL TESTS PASSED${NC}"
  echo -e "${GREEN}═══════════════════════════════════════════════════════════════════${NC}"
  exit 0
else
  echo -e "${RED}═══════════════════════════════════════════════════════════════════${NC}"
  echo -e "${RED}  ❌ SOME TESTS FAILED${NC}"
  echo -e "${RED}═══════════════════════════════════════════════════════════════════${NC}"
  exit 1
fi
