#!/usr/bin/env bash
# ╔══════════════════════════════════════════════════════════════════════════════╗
# ║                    T01 - Theme Module Automated Tests                        ║
# ╚══════════════════════════════════════════════════════════════════════════════╝
#
# Host: imac0
# Theme: lightGray (Workstation - Home)
# Tests: Starship, Zellij, Eza configuration verification
#
# Usage: ./T01-theme.sh
#

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Counters
PASSED=0
FAILED=0
TOTAL=0

# ════════════════════════════════════════════════════════════════════════════════
# Helper Functions
# ════════════════════════════════════════════════════════════════════════════════

print_header() {
  echo ""
  echo -e "${BLUE}════════════════════════════════════════════════════════════════${NC}"
  echo -e "${BLUE}  $1${NC}"
  echo -e "${BLUE}════════════════════════════════════════════════════════════════${NC}"
}

print_test() {
  echo -e "\n${YELLOW}▶ $1${NC}"
  ((TOTAL++)) || true
}

pass() {
  echo -e "${GREEN}  ✅ PASS: $1${NC}"
  ((PASSED++)) || true
}

fail() {
  echo -e "${RED}  ❌ FAIL: $1${NC}"
  ((FAILED++)) || true
}

check_file_exists() {
  if [[ -f "$1" ]]; then
    pass "File exists: $1"
    return 0
  else
    fail "File missing: $1"
    return 1
  fi
}

check_file_contains() {
  local file="$1"
  local pattern="$2"
  local description="$3"

  if grep -q "$pattern" "$file" 2>/dev/null; then
    pass "$description"
    return 0
  else
    fail "$description (pattern not found: $pattern)"
    return 1
  fi
}

# ════════════════════════════════════════════════════════════════════════════════
# Test Suite
# ════════════════════════════════════════════════════════════════════════════════

print_header "T01 - Theme Module Tests (imac0 / lightGray)"

echo "Host: $(hostname)"
echo "Date: $(date)"

# ────────────────────────────────────────────────────────────────────────────────
# T01.1 - Starship Configuration File
# ────────────────────────────────────────────────────────────────────────────────

print_test "T01.1 - Starship Configuration"

check_file_exists "$HOME/.config/starship.toml"
check_file_contains "$HOME/.config/starship.toml" "imac0" "Starship config mentions hostname 'imac0'"
check_file_contains "$HOME/.config/starship.toml" "Light Gray" "Starship config mentions 'Light Gray' theme"
check_file_contains "$HOME/.config/starship.toml" "theme-hm.nix" "Starship config auto-generated by theme-hm.nix"
check_file_contains "$HOME/.config/starship.toml" "lightGray" "Starship config uses lightGray palette"

# ────────────────────────────────────────────────────────────────────────────────
# T01.2 - Starship Features
# ────────────────────────────────────────────────────────────────────────────────

print_test "T01.2 - Starship Features"

check_file_contains "$HOME/.config/starship.toml" "custom.root_alert" "Root alert segment configured"
check_file_contains "$HOME/.config/starship.toml" '\[status\]' "Exit status module configured"
check_file_contains "$HOME/.config/starship.toml" '\[sudo\]' "Sudo indicator configured"
check_file_contains "$HOME/.config/starship.toml" '\[cmd_duration\]' "Command duration configured"
check_file_contains "$HOME/.config/starship.toml" '\[jobs\]' "Background jobs configured"

# ────────────────────────────────────────────────────────────────────────────────
# T01.3 - Starship Color Values (lightGray palette)
# ────────────────────────────────────────────────────────────────────────────────

print_test "T01.3 - Starship Colors (lightGray palette)"

# These are the lightGray gradient colors from theme-palettes.nix
check_file_contains "$HOME/.config/starship.toml" "#e0e2e8" "Lightest gradient color present"
check_file_contains "$HOME/.config/starship.toml" "#a8aeb8" "Primary gradient color present"
check_file_contains "$HOME/.config/starship.toml" "#888e98" "Secondary gradient color present"
check_file_contains "$HOME/.config/starship.toml" "#181a1c" "Darkest gradient color present"

# ────────────────────────────────────────────────────────────────────────────────
# T01.4 - Zellij Configuration File
# ────────────────────────────────────────────────────────────────────────────────

print_test "T01.4 - Zellij Configuration"

check_file_exists "$HOME/.config/zellij/config.kdl"
check_file_contains "$HOME/.config/zellij/config.kdl" "imac0" "Zellij config mentions hostname 'imac0'"
check_file_contains "$HOME/.config/zellij/config.kdl" "Light Gray" "Zellij config mentions 'Light Gray' theme"
check_file_contains "$HOME/.config/zellij/config.kdl" "theme-hm.nix" "Zellij config auto-generated by theme-hm.nix"

# ────────────────────────────────────────────────────────────────────────────────
# T01.5 - Zellij Theme Definition
# ────────────────────────────────────────────────────────────────────────────────

print_test "T01.5 - Zellij Theme"

check_file_contains "$HOME/.config/zellij/config.kdl" 'theme "imac0"' "Zellij uses hostname as theme name"
check_file_contains "$HOME/.config/zellij/config.kdl" "imac0 {" "Zellij theme block defined for imac0"
check_file_contains "$HOME/.config/zellij/config.kdl" 'default_shell "fish"' "Zellij default shell is fish"

# ────────────────────────────────────────────────────────────────────────────────
# T01.6 - Zellij Keybindings
# ────────────────────────────────────────────────────────────────────────────────

print_test "T01.6 - Zellij Keybindings"

check_file_contains "$HOME/.config/zellij/config.kdl" 'bind "Ctrl e"' "Ctrl+e keybinding configured"
check_file_contains "$HOME/.config/zellij/config.kdl" 'unbind "Ctrl o"' "Ctrl+o unbound"
check_file_contains "$HOME/.config/zellij/config.kdl" 'bind "Ctrl a"' "Ctrl+a keybinding configured"

# ────────────────────────────────────────────────────────────────────────────────
# T01.7 - Eza Colors File (backup check)
# ────────────────────────────────────────────────────────────────────────────────

print_test "T01.7 - Eza Colors in Session Vars File"

# Check session variables file exists (for bash compatibility)
HM_SESSION_VARS="$HOME/.nix-profile/etc/profile.d/hm-session-vars.sh"
if [[ -f "$HM_SESSION_VARS" ]]; then
  check_file_contains "$HM_SESSION_VARS" "EZA_COLORS" "EZA_COLORS defined in hm-session-vars.sh"
  check_file_contains "$HM_SESSION_VARS" "LS_COLORS" "LS_COLORS defined in hm-session-vars.sh"
else
  fail "Session vars file not found: $HM_SESSION_VARS"
fi

# ────────────────────────────────────────────────────────────────────────────────
# T01.8 - Eza Colors (Fish Environment - CRITICAL)
# ────────────────────────────────────────────────────────────────────────────────

print_test "T01.8 - Eza Colors in Fish Shell"

# Check that EZA_COLORS is actually set in fish (not just in a file)
# This is CRITICAL - the file may exist but fish may not source it!

check_fish_var() {
  local var_name="$1"
  local expected_pattern="$2"
  local description="$3"

  # Run fish INTERACTIVELY (-i) to get the actual variable value
  # (interactiveShellInit only runs in interactive mode)
  local value
  value=$(fish -i -c "echo \$$var_name" 2>/dev/null)

  if [[ -n "$value" ]] && echo "$value" | grep -q "$expected_pattern"; then
    pass "$description"
    return 0
  elif [[ -z "$value" ]]; then
    fail "$description (variable not set in fish!)"
    return 1
  else
    fail "$description (pattern '$expected_pattern' not in value)"
    return 1
  fi
}

check_fish_var "EZA_COLORS" "di=1;38;5;110" "EZA_COLORS set in fish with soft blue directories"
check_fish_var "EZA_COLORS" "ex=38;5;114" "EZA_COLORS has muted green executables"
check_fish_var "EZA_COLORS" "ln=38;5;116" "EZA_COLORS has soft cyan symlinks"
check_fish_var "EZA_COLORS" "or=38;5;167" "EZA_COLORS has warning red for broken links"
check_fish_var "LS_COLORS" "di=1;38;5;110" "LS_COLORS set in fish for compatibility"

# ────────────────────────────────────────────────────────────────────────────────
# T01.9 - Unicode/Nerd Font Icons (CRITICAL - prevents corruption)
# ────────────────────────────────────────────────────────────────────────────────

print_test "T01.9 - Unicode/Nerd Font Icons"

# These are the critical Unicode characters that must be preserved
# If any of these fail, the template generation has corrupted Unicode!

STARSHIP_TOML="$HOME/.config/starship.toml"

# Check for Unicode characters using Python (most reliable for UTF-8)
check_unicode_python() {
  local file="$1"
  local codepoint="$2"
  local description="$3"

  if python3 -c "
import sys
with open('$file', 'r') as f:
    content = f.read()
char = chr($codepoint)
sys.exit(0 if char in content else 1)
" 2>/dev/null; then
    pass "$description"
    return 0
  else
    fail "$description (U+$(printf '%04X' "$codepoint") not found)"
    return 1
  fi
}

# Rounded powerline arrows (CRITICAL - these broke multiple times today)
check_unicode_python "$STARSHIP_TOML" 0xE0B4 "Rounded right arrow (U+E0B4) present"
check_unicode_python "$STARSHIP_TOML" 0xE0B6 "Rounded left arrow (U+E0B6) present"

# OS icons
check_unicode_python "$STARSHIP_TOML" 0xF179 "Apple icon (U+F179) present"
check_unicode_python "$STARSHIP_TOML" 0xF313 "NixOS icon (U+F313) present"
check_unicode_python "$STARSHIP_TOML" 0xF17C "Linux icon (U+F17C) present"

# Git icon
check_unicode_python "$STARSHIP_TOML" 0xF418 "Git branch icon (U+F418) present"

# Time/clock icon
check_unicode_python "$STARSHIP_TOML" 0xF43A "Clock icon (U+F43A) present"

# Language icons
check_unicode_python "$STARSHIP_TOML" 0xE718 "Node.js icon (U+E718) present"
check_unicode_python "$STARSHIP_TOML" 0xE73C "Python icon (U+E73C) present"

# Special characters (should be ASCII-safe but verify)
check_file_contains "$STARSHIP_TOML" "░▒▓" "Gradient shading characters present"
check_file_contains "$STARSHIP_TOML" "❯" "Success prompt character present"
check_file_contains "$STARSHIP_TOML" "✗" "Error prompt character present"
check_file_contains "$STARSHIP_TOML" "⚠" "Root warning symbol present"
check_file_contains "$STARSHIP_TOML" "⏱" "Stopwatch symbol present"
check_file_contains "$STARSHIP_TOML" "✦" "Jobs star symbol present"

# ────────────────────────────────────────────────────────────────────────────────
# T01.10 - Theme Module Integration
# ────────────────────────────────────────────────────────────────────────────────

print_test "T01.10 - Theme Module Integration"

# Check that all three configs have consistent theme info
if grep -q "lightGray" "$HOME/.config/starship.toml" &&
  grep -q "lightGray" "$HOME/.config/zellij/config.kdl"; then
  pass "All configs use consistent lightGray palette"
else
  fail "Palette inconsistency between configs"
fi

if grep -q "theme-hm.nix" "$HOME/.config/starship.toml" &&
  grep -q "theme-hm.nix" "$HOME/.config/zellij/config.kdl"; then
  pass "All configs generated by theme-hm.nix"
else
  fail "Not all configs generated by theme-hm.nix"
fi

# ════════════════════════════════════════════════════════════════════════════════
# Summary
# ════════════════════════════════════════════════════════════════════════════════

print_header "Test Summary"

echo ""
echo -e "  Total:  ${TOTAL}"
echo -e "  ${GREEN}Passed: ${PASSED}${NC}"
echo -e "  ${RED}Failed: ${FAILED}${NC}"
echo ""

if [[ $FAILED -eq 0 ]]; then
  echo -e "${GREEN}═══════════════════════════════════════════════════════════════════${NC}"
  echo -e "${GREEN}  ✅ ALL TESTS PASSED${NC}"
  echo -e "${GREEN}═══════════════════════════════════════════════════════════════════${NC}"
  exit 0
else
  echo -e "${RED}═══════════════════════════════════════════════════════════════════${NC}"
  echo -e "${RED}  ❌ SOME TESTS FAILED${NC}"
  echo -e "${RED}═══════════════════════════════════════════════════════════════════${NC}"
  exit 1
fi
