[project]
name = "janus-managed-services"
revision = "1.0"

[profiles.production]
MANAGED_SERVICE_CANARY_API_TOKEN = { description = "Managed service canary API token", required = true }
PPM_PAIMOS_SECRET_KEY = { description = "PPM encryption key", required = true }
PPM_SMTP_PASS = { description = "PPM SMTP password", required = true }
PPM_OIDC_CLIENT_SECRET = { description = "PPM OIDC client secret", required = true }
