# Placeholder - hardware-configuration.nix for hsb2
# STATUS: ARCHIVED/INACTIVE - Host running Raspbian (not NixOS)
#
# This file is kept for reference only.
# NixOS migration was abandoned due to ARMv6l complexity.
# See README.md for current Raspbian management instructions.
#
# This file would have been auto-generated by nixos-generate-config on the target machine
#
# To generate:
# 1. Boot NixOS on Raspberry Pi
# 2. Run: nixos-generate-config --root /mnt
# 3. Copy /mnt/etc/nixos/hardware-configuration.nix to this location
#
# For Raspberry Pi Zero W (armv6l), special kernel and bootloader settings are required.

{
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/sd-card/sd-image-raspberrypi.nix")
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # Placeholder settings - replace after generation
  boot.initrd.availableKernelModules = [ ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  # NOTE: Filesystems are defined in disk-config.nix via disko
  # Do not define fileSystems here to avoid conflicts

  swapDevices = [ ];

  # Raspberry Pi CPU settings
  nixpkgs.hostPlatform = lib.mkDefault "armv6l-linux";
  nixpkgs.buildPlatform = lib.mkDefault "x86_64-linux";
  nixpkgs.config.allowUnsupportedSystem = true;

  # Disable ZFS on 32-bit ARM
  boot.supportedFilesystems.zfs = lib.mkForce false;
}
