# Placeholder - hardware-configuration.nix for hsb2
# This file is auto-generated by nixos-generate-config on the target machine
#
# To generate:
# 1. Boot NixOS on Raspberry Pi
# 2. Run: nixos-generate-config --root /mnt
# 3. Copy /mnt/etc/nixos/hardware-configuration.nix to this location
#
# For Raspberry Pi Zero W (armv6l), special kernel and bootloader settings are required.

{
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # Placeholder settings - replace after generation
  boot.initrd.availableKernelModules = [ ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  # NOTE: Filesystems are defined in disk-config.nix via disko
  # Do not define fileSystems here to avoid conflicts

  swapDevices = [ ];

  # Raspberry Pi CPU settings
  nixpkgs.hostPlatform = lib.mkDefault "armv6l-linux";
  # nixpkgs.config.allowUnsupportedSystem = true; # Removed to fix cross-compilation issue

  # Disable ZFS on 32-bit ARM
  boot.supportedFilesystems.zfs = lib.mkForce false;
}
