#!/usr/bin/env bash
# ╔══════════════════════════════════════════════════════════════════════════════╗
# ║                    T01 - Theme Module Automated Tests                        ║
# ╚══════════════════════════════════════════════════════════════════════════════╝
#
# Host: hsb0
# Theme: yellow (Home - DNS/DHCP - be careful!)
# Tests: Starship, Zellij, Eza configuration verification
#
# Usage: ./T01-theme.sh
#

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Counters
PASSED=0
FAILED=0
TOTAL=0

# ════════════════════════════════════════════════════════════════════════════════
# Helper Functions
# ════════════════════════════════════════════════════════════════════════════════

print_header() {
  echo ""
  echo -e "${BLUE}════════════════════════════════════════════════════════════════${NC}"
  echo -e "${BLUE}  $1${NC}"
  echo -e "${BLUE}════════════════════════════════════════════════════════════════${NC}"
}

print_test() {
  echo -e "\n${YELLOW}▶ $1${NC}"
  ((TOTAL++)) || true
}

pass() {
  echo -e "${GREEN}  ✅ PASS: $1${NC}"
  ((PASSED++)) || true
}

fail() {
  echo -e "${RED}  ❌ FAIL: $1${NC}"
  ((FAILED++)) || true
}

check_file_exists() {
  if [[ -f "$1" ]]; then
    pass "File exists: $1"
    return 0
  else
    fail "File missing: $1"
    return 1
  fi
}

check_file_contains() {
  local file="$1"
  local pattern="$2"
  local description="$3"

  if grep -q "$pattern" "$file" 2>/dev/null; then
    pass "$description"
    return 0
  else
    fail "$description (pattern not found: $pattern)"
    return 1
  fi
}

# ════════════════════════════════════════════════════════════════════════════════
# Test Suite
# ════════════════════════════════════════════════════════════════════════════════

print_header "T01 - Theme Module Tests (hsb0 / yellow)"

echo "Host: $(hostname)"
echo "Date: $(date)"

# ────────────────────────────────────────────────────────────────────────────────
# T01.1 - Starship Configuration File
# ────────────────────────────────────────────────────────────────────────────────

print_test "T01.1 - Starship Configuration"

STARSHIP_CONFIG="$HOME/.config/starship.toml"
check_file_exists "$STARSHIP_CONFIG"
check_file_contains "$STARSHIP_CONFIG" "hsb0" "Starship config mentions hostname 'hsb0'"
check_file_contains "$STARSHIP_CONFIG" "Yellow" "Starship config mentions 'Yellow' theme"
check_file_contains "$STARSHIP_CONFIG" "theme-hm.nix" "Starship config auto-generated by theme-hm.nix"
check_file_contains "$STARSHIP_CONFIG" "yellow" "Starship config uses yellow palette"

# ────────────────────────────────────────────────────────────────────────────────
# T01.2 - Starship Features
# ────────────────────────────────────────────────────────────────────────────────

print_test "T01.2 - Starship Features"

check_file_contains "$STARSHIP_CONFIG" "custom.root_alert" "Root alert segment configured"
check_file_contains "$STARSHIP_CONFIG" '\[status\]' "Exit status module configured"
check_file_contains "$STARSHIP_CONFIG" '\[sudo\]' "Sudo indicator configured"
check_file_contains "$STARSHIP_CONFIG" '\[cmd_duration\]' "Command duration configured"
check_file_contains "$STARSHIP_CONFIG" '\[jobs\]' "Background jobs configured"

# ────────────────────────────────────────────────────────────────────────────────
# T01.3 - Starship Yellow Palette Colors
# ────────────────────────────────────────────────────────────────────────────────

print_test "T01.3 - Starship Colors (yellow palette)"

# These are the yellow gradient colors from theme-palettes.nix
check_file_contains "$STARSHIP_CONFIG" "#e8e0a8" "Lightest gradient color (yellow) present"
check_file_contains "$STARSHIP_CONFIG" "#d4c060" "Primary gradient color (yellow) present"
check_file_contains "$STARSHIP_CONFIG" "#a89840" "Secondary gradient color (yellow) present"

# ────────────────────────────────────────────────────────────────────────────────
# T01.4 - Zellij Configuration File
# ────────────────────────────────────────────────────────────────────────────────

print_test "T01.4 - Zellij Configuration"

ZELLIJ_CONFIG="$HOME/.config/zellij/config.kdl"
check_file_exists "$ZELLIJ_CONFIG"
check_file_contains "$ZELLIJ_CONFIG" "hsb0" "Zellij config mentions hostname 'hsb0'"
check_file_contains "$ZELLIJ_CONFIG" "Yellow" "Zellij config mentions 'Yellow' theme"
check_file_contains "$ZELLIJ_CONFIG" "theme-hm.nix" "Zellij config auto-generated by theme-hm.nix"

# ────────────────────────────────────────────────────────────────────────────────
# T01.5 - Zellij Theme Definition
# ────────────────────────────────────────────────────────────────────────────────

print_test "T01.5 - Zellij Theme"

check_file_contains "$ZELLIJ_CONFIG" 'theme "hsb0"' "Zellij uses hostname as theme name"
check_file_contains "$ZELLIJ_CONFIG" "hsb0 {" "Zellij theme block defined for hsb0"
check_file_contains "$ZELLIJ_CONFIG" 'default_shell "fish"' "Zellij default shell is fish"

# ────────────────────────────────────────────────────────────────────────────────
# T01.6 - Eza Theme File
# ────────────────────────────────────────────────────────────────────────────────

print_test "T01.6 - Eza Theme File"

EZA_THEME_FILE="$HOME/.config/eza/theme.yml"
check_file_exists "$EZA_THEME_FILE"
check_file_contains "$EZA_THEME_FILE" "Tokyo Night" "Theme based on Tokyo Night"
check_file_contains "$EZA_THEME_FILE" "sysop" "Sysop-focused modifications"

# ────────────────────────────────────────────────────────────────────────────────
# T01.7 - Eza Theme Sysop Features
# ────────────────────────────────────────────────────────────────────────────────

print_test "T01.7 - Eza Theme Sysop Features"

check_file_contains "$EZA_THEME_FILE" 'directory:.*bold: true' "Directories are bold"
check_file_contains "$EZA_THEME_FILE" 'executable:.*bold: true' "Executables are bold"

# ────────────────────────────────────────────────────────────────────────────────
# T01.8 - Eza Theme Applied
# ────────────────────────────────────────────────────────────────────────────────

print_test "T01.8 - Eza Theme Applied"

# Check EZA_CONFIG_DIR is set in fish config
FISH_CONFIG="$HOME/.config/fish/config.fish"
if grep -q "EZA_CONFIG_DIR" "$FISH_CONFIG" 2>/dev/null; then
  pass "EZA_CONFIG_DIR is configured in fish config"
else
  fail "EZA_CONFIG_DIR not set in fish config!"
fi

# Test that eza actually uses RGB colors (use -la on / to get detailed output with colors)
EZA_OUTPUT=$(EZA_CONFIG_DIR="$HOME/.config/eza" eza --color=always -la / 2>/dev/null || true)
if echo "$EZA_OUTPUT" | grep -q '38;2;'; then
  pass "Eza uses RGB colors from theme (38;2;r;g;b format)"
else
  fail "Eza NOT using theme colors!"
fi

# ════════════════════════════════════════════════════════════════════════════════
# Summary
# ════════════════════════════════════════════════════════════════════════════════

print_header "Test Summary"

echo ""
echo -e "  Total:  ${TOTAL}"
echo -e "  ${GREEN}Passed: ${PASSED}${NC}"
echo -e "  ${RED}Failed: ${FAILED}${NC}"
echo ""

if [[ $FAILED -eq 0 ]]; then
  echo -e "${GREEN}═══════════════════════════════════════════════════════════════════${NC}"
  echo -e "${GREEN}  ✅ ALL TESTS PASSED${NC}"
  echo -e "${GREEN}═══════════════════════════════════════════════════════════════════${NC}"
  exit 0
else
  echo -e "${RED}═══════════════════════════════════════════════════════════════════${NC}"
  echo -e "${RED}  ❌ SOME TESTS FAILED${NC}"
  echo -e "${RED}═══════════════════════════════════════════════════════════════════${NC}"
  exit 1
fi
