#!/usr/bin/env python3
"""Regenerate the canonical shell icon data without Unicode copy/paste damage."""
from pathlib import Path

icons = {'CPU': 0xF4BC, 'RAM': 0xEFC5, 'LOAD': 0xF029A, 'SWAP': 0xF0FB4}
header = '''#!/usr/bin/env bash
# StaSysMo Icons - Generated by generate-icons.py to preserve Unicode
# DO NOT EDIT MANUALLY - Regenerate with the adjacent Python helper
# See: modules/uzumaki/stasysmo/README.md
# shellcheck disable=SC2034  # Variables are used when sourced

'''
Path(__file__).with_name('icons.sh').write_text(
    header + ''.join(f'{name}_ICON="{chr(code)}"\n' for name, code in icons.items()),
    encoding='utf-8',
)
