#!/usr/bin/env bash
# StaSysMo Icons - Generated by generate-icons.py to preserve Unicode
# DO NOT EDIT MANUALLY - Regenerate with the adjacent Python helper
# See: modules/uzumaki/stasysmo/README.md
# shellcheck disable=SC2034  # Variables are used when sourced

CPU_ICON=""
RAM_ICON=""
LOAD_ICON="󰊚"
SWAP_ICON="󰾴"
