#!/usr/bin/env bash
# T04: WezTerm Terminal - Automated Test
set -euo pipefail

GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo "=== T04: WezTerm Terminal Test ==="
echo

PASSED=0
FAILED=0

# Test 1: WezTerm CLI installed
echo -n "Test 1: WezTerm CLI installed... "
if command -v wezterm >/dev/null 2>&1; then
  WEZTERM_VERSION=$(wezterm --version 2>/dev/null | head -1)
  echo -e "${GREEN}✅ PASS${NC} ($WEZTERM_VERSION)"
  ((PASSED++))
else
  echo -e "${RED}❌ FAIL${NC}"
  ((FAILED++))
fi

# Test 2: WezTerm from Nix
echo -n "Test 2: WezTerm from Nix... "
WEZTERM_PATH=$(which wezterm 2>/dev/null || echo "not found")
if [[ "$WEZTERM_PATH" == *".nix-profile"* ]] || [[ "$WEZTERM_PATH" == *"/nix/store"* ]]; then
  echo -e "${GREEN}✅ PASS${NC}"
  ((PASSED++))
else
  echo -e "${RED}❌ FAIL${NC} (found at $WEZTERM_PATH)"
  ((FAILED++))
fi

# Test 3: WezTerm config exists
echo -n "Test 3: WezTerm config exists... "
if [ -f "$HOME/.config/wezterm/wezterm.lua" ] || [ -f "$HOME/.wezterm.lua" ]; then
  echo -e "${GREEN}✅ PASS${NC}"
  ((PASSED++))
else
  echo -e "${YELLOW}⚠️ WARN${NC} (config generated by home-manager)"
  ((PASSED++))
fi

# Test 4: WezTerm app in Applications
echo -n "Test 4: WezTerm.app available... "
if [ -e "$HOME/Applications/WezTerm.app" ] || [ -e "$HOME/Applications/Home Manager Apps/WezTerm.app" ]; then
  echo -e "${GREEN}✅ PASS${NC}"
  ((PASSED++))
else
  echo -e "${YELLOW}⚠️ WARN${NC} (app not symlinked yet)"
  ((PASSED++))
fi

echo
echo "Results: $PASSED passed, $FAILED failed"
if [ $FAILED -eq 0 ]; then
  echo -e "${GREEN}🎉 All tests passed!${NC}"
  exit 0
else
  echo -e "${RED}❌ Some tests failed${NC}"
  exit 1
fi
