#!/usr/bin/env bash
# Formatting/lint gate — NIX-334.
#
# WHY THIS EXISTS
# ===============
# CI used to run `devenv shell --quiet -- prek run …`, ~7 minutes per PR. Almost
# none of it was formatting: 403 of 436 seconds went on realising a devenv
# environment. Two compounding causes:
#
#   * the generated .pre-commit-config.yaml pins ABSOLUTE STORE PATHS for every
#     hook entry, so it cannot be used without building that exact closure
#   * devenv.yaml pins nixpkgs to github:cachix/devenv-nixpkgs/rolling -- a
#     different nixpkgs from the flake's -- so those paths are NOT in
#     cache.nixos.org. The only substituter that had them was
#     cachix://pbek-nixcfg-devenv, inherited with this repo's lineage, with
#     pushing DISABLED. Any divergence from pbek's closure was a permanent cache
#     miss that could never heal; on 2026-07-30 it made the required check fail
#     outright on devenv-2.2.0.drv, blocking a merge for reasons unrelated to the
#     code under review.
#
# This runs the same tools straight from nixpkgs, where they are cached upstream,
# so the gate finishes in about a second and depends on nobody else's cache.
#
# IT MIRRORS THE LOCAL HOOKS EXACTLY
# ==================================
# The invocations below were read out of the generated .pre-commit-config.yaml,
# not guessed. Note the hooks FORMAT IN PLACE (deadnix --edit, bare nixfmt,
# shfmt -i 2 -w, prettier --write) and the gate is then `git diff --exit-code`:
# "run the formatters -- did anything change?" Two of them are pure checkers
# (shellcheck, statix) whose exit status matters directly.
#
# If a hook is added to devenv.nix, add it here too. The lists can drift; that
# trade was made knowingly against a 7-minute environment build per PR.
#
# SCOPE
# =====
# With BASE_REVISION set (CI on a PR) only files changed against that ref are
# touched, matching prek's --from-ref/--to-ref. Without it, all tracked files.
# The distinction matters: the repo carries a little pre-existing formatting debt
# outside doctrine, and a whole-repo gate would fail every PR on files nobody
# touched.
#
# Written for bash 3.2 (macOS ships it): no mapfile, no associative arrays.
# See tests/T33-bash-version-guards.sh for why that is enforced here.
set -uo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.." || exit 1

BASE_REVISION="${BASE_REVISION:-}"
status=0

note() { printf '\n\033[1m== %s\033[0m\n' "$1"; }
fail() {
  printf '\033[31mFAIL\033[0m %s\n' "$1"
  status=1
}

# doctrine/ is the inspr-modules submodule -- upstream, own lint pipeline.
# hardware-configuration.nix is generated by nixos-generate-config.
list_files() {
  if [ -n "$BASE_REVISION" ]; then
    git diff --name-only --diff-filter=ACMR "$BASE_REVISION"...HEAD
  else
    git ls-files
  fi | grep -E "$1" | grep -vE '^doctrine/' | grep -vE 'hardware-configuration\.nix$' || true
}

# bash 3.2: no mapfile. Keep newline-separated strings, drop deleted paths.
collect() {
  _out=""
  while IFS= read -r line; do
    [ -n "$line" ] || continue
    [ -e "$line" ] || continue
    _out="$_out$line"$'\n'
  done
  printf '%s' "$_out"
}

count() { if [ -z "$1" ]; then echo 0; else printf '%s\n' "$1" | grep -c .; fi; }

run_over() { # run_over <label> <file-list> <cmd...>
  label="$1"
  files="$2"
  shift 2
  note "$label ($(count "$files") files)"
  if [ -z "$files" ]; then
    printf 'nothing to check\n'
    return
  fi
  printf '%s' "$files" | tr '\n' '\0' | xargs -0 "$@" || fail "$label: see above"
}

nix_files="$(list_files '\.nix$' | collect)"
sh_files="$(list_files '\.(sh|bash)$' | collect)"
doc_files="$(list_files '\.(js|json|md|yaml|yml|vue)$' | collect)"
just_files="$(list_files '(^|/)(justfile|Justfile)$' | collect)"

# ── formatters: write in place, then `git diff --exit-code` is the verdict ──
run_over nixfmt "$nix_files" nixfmt
run_over deadnix "$nix_files" deadnix --edit --fail
run_over shfmt "$sh_files" shfmt -i 2 -w
run_over prettier "$doc_files" prettier --ignore-unknown --list-different --write
if [ -n "$just_files" ] && command -v just >/dev/null 2>&1; then
  run_over just "$just_files" just --fmt --unstable --justfile
fi

# ── pure checkers: exit status is the verdict ──
run_over shellcheck "$sh_files" shellcheck

note "statix"
statix check --format errfmt --ignore hardware-configuration.nix doctrine || fail "statix: see above"

note "tree unchanged?"
if git diff --exit-code; then
  printf 'no formatter rewrote anything\n'
else
  fail "the formatters rewrote files -- commit the diff above"
fi

if [ "$status" -ne 0 ]; then
  printf '\n\033[31mformatting gate failed\033[0m\n'
else
  printf '\n\033[32mformatting gate passed\033[0m\n'
fi
exit "$status"
