name: 📄 Check formatting

on:
  pull_request:

jobs:
  format-check:
    name: 📄 Check code formatting with "just format"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: 🧰 Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: ⚙️ Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: 🔒 Cache dependencies
        uses: cachix/cachix-action@v16
        with:
          # https://app.cachix.org/cache/pbek-nixcfg-devenv
          name: pbek-nixcfg-devenv
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: 🔧 Install devenv.sh
        run: nix profile add nixpkgs#devenv
      - name: 🌳 Check changed-file formatting
        env:
          BASE_REVISION: ${{ github.event.pull_request.base.sha }}
          HEAD_REVISION: ${{ github.event.pull_request.head.sha }}
        run: |
          devenv shell --quiet -- prek run \
            --from-ref "$BASE_REVISION" \
            --to-ref "$HEAD_REVISION"
          git diff --exit-code
